### ISSUE TITLE
bug: None of the requested orientations are supported by the view controller. Requested: portrait; Supported: landscapeRight

### ISSUE THREAD

**Issue by evanlegamer** [capawesome-team/capacitor-plugins#100]
### Plugin(s)

- [ ] Android Foreground Service
- [ ] Android Battery Optimization
- [ ] App Update
- [ ] Background Task
- [ ] Badge
- [ ] Cloudinary
- [ ] Datetime Picker
- [ ] File Opener
- [ ] File Picker
- [ ] Managed Configurations
- [ ] NFC
- [ ] Photo Editor
- [X] Screen Orientation

### Version

5.0.0

### Platform(s)

- [ ] Android
- [X] iOS
- [ ] Web

### Current behavior

Got this warning in xcode console while testing the app. requestGeometryUpdate failed. Error Domain=UISceneErrorDomain Code=101 "None of the requested orientations are supported by the view controller. Requested: portrait; Supported: landscapeRight" UserInfo={NSLocalizedDescription=None of the requested orientations are supported by the view controller. Requested: portrait; Supported: landscapeRight}

### Expected behavior

No warning

### Reproduction

no reproduction

### Steps to reproduce

just call
```js
await ScreenOrientation.lock({ type: OrientationType.PORTRAIT });
```

### Capacitor doctor

💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 5.5.1
  @capacitor/core: 5.5.1
  @capacitor/android: 5.5.1
  @capacitor/ios: 5.5.1

Installed Dependencies:

  @capacitor/android: 5.3.0
  @capacitor/core: 5.3.0
  @capacitor/ios: 5.3.0
  @capacitor/cli: 5.3.0

[success] iOS looking great! 👌
[success] Android looking great! 👌

### Before submitting

- [X] I have read and followed the [bug report guidelines](https://capawesome.io/contributing/bug-reports/).
- [X] I have attached links to possibly related issues and discussions.
- [X] I understand that incomplete issues (e.g. without reproduction) are closed.

**Comment by robingenz** [comment]
This error is caused by [this line](https://github.com/capawesome-team/capacitor-plugins/blob/bf8935b22828f5e7306477010a2c5b91edeaf6d1/packages/screen-orientation/ios/Plugin/ScreenOrientation.swift#L33).
This line was added by the following PR: https://github.com/capawesome-team/capacitor-screen-orientation/pull/14
It seems like this fix is not necessary on iOS 16.
