### ISSUE TITLE
⚡ Capacitor 6

### ISSUE THREAD

**Issue by robingenz** [capawesome-team/capacitor-plugins#103]
According to [this blog post](https://ionic.io/blog/introducing-a-new-capacitor-release-cadence), Capacitor 6 will be the `latest` version from February 2024. From this point on, all plugins in this repository should also support Capacitor 6. Capacitor 5 will no longer be supported from this date.

**Comment by ptmkenny** [comment]
[6.0-rc0](https://github.com/ionic-team/capacitor/releases/tag/6.0.0-rc.0) was released last month and the VSCode Ionic extension is now offering to upgrade projects from 5 to 6.  It would be great if support for 6 was added soon.

**Comment by robingenz** [comment]
@ptmkenny This is just a release candidate, not the final version. Last year there were also some changes in the final version. This may not be a problem with 2-3 plugins, but with 30 plugins it's a lot of work.

**Comment by ptmkenny** [comment]
Thanks for the update.  It's good to have clarification that the plugins will be updated after 6 releases officially instead of before.
