### ISSUE TITLE
feat(file-picker): set ordered selection type in media picker (ios only)

### ISSUE THREAD

**Issue by stephan-fischer** [capawesome-team/capacitor-plugins#114]
### Plugin(s)

- [ ] Android Foreground Service
- [ ] Android Battery Optimization
- [ ] App Update
- [ ] Background Task
- [ ] Badge
- [ ] Cloudinary
- [ ] Datetime Picker
- [ ] File Opener
- [X] File Picker
- [ ] Managed Configurations
- [ ] NFC
- [ ] Photo Editor
- [ ] Screen Orientation

### Current problem

Nobody knows currently in which order the media is selected on ios, because currently a
checkmark appears.

### Preferred solution

A parameter to set an ordered view would be nice, like

```
  const media = await FilePicker.pickImages({
            multiple: true,
            readData: false,
            limit: 5,
            ordered: true
 });
```
To solve this in ios swift, this code will achieve this:

`configuration.selection = . ordered`

With this selection the user can see the ordering. (Screenshots attached).

Useful links:
[PHPickerConfiguration.Selection](https://developer.apple.com/documentation/photokit/phpickerconfiguration/selection)

### Before submitting

- [X] I have read and followed the [feature request guidelines](https://capawesome.io/contributing/feature-requests/).
- [X] I have attached links to possibly related issues and discussions.

# Screenshots

<img src="https://github.com/capawesome-team/capacitor-plugins/assets/2657649/96d12551-08d2-4829-a090-aa55523eb0f7" width="400" style="float: left">
<img src="https://github.com/capawesome-team/capacitor-plugins/assets/2657649/19f002f7-dde3-4b8a-abf0-e2f7bdcfa955" width="400" style="float: left">

**Comment by robingenz** [comment]
Great idea! Would you be willing to create a PR?

**Comment by stephan-fischer** [comment]
hell yes 😊 !
