### ISSUE TITLE
feat: current and available version name alongside current and available version codes

### ISSUE THREAD

**Issue by priithansen** [capawesome-team/capacitor-plugins#115]
### Plugin(s)

- [ ] Android Foreground Service
- [ ] Android Battery Optimization
- [X] App Update
- [ ] Background Task
- [ ] Badge
- [ ] Cloudinary
- [ ] Datetime Picker
- [ ] File Opener
- [ ] File Picker
- [ ] Managed Configurations
- [ ] NFC
- [ ] Photo Editor
- [ ] Screen Orientation

### Current problem

Would like to use the App-update plugin to motivate users updating when there are major version updates. For iOS the plugin currently shows the "brand version" that is semver compatible but with Android version code there is no way to differentiate between updates if it's major, minor or patch. 

### Preferred solution

Would it be possible for this plugin to also surface what Android seem to call versionName?
Maybe have 4 new properties to the `AppUpdateInfo` result object to avoid breaking changes before removing old keys in some future major version change.

```
example: 

// iOS: CFBundleShortVersionString |  Android: versionName
currentVersionName: 1.0.1
availableVersionName: 2.0.0

// iOS: CFBundleVersion | Android: versionCode
currentVersionCode: 120
availableVersionCode: 129

// Existing keys showing kind of opposites for each platform left to avoid breaking changes.
currentVersion: 
availableVersion
```

### Before submitting

- [X] I have read and followed the [feature request guidelines](https://capawesome.io/contributing/feature-requests/).
- [X] I have attached links to possibly related issues and discussions.

**Comment by priithansen** [comment]
After doing some digging in the plugin source (as a complete noob of java and swift) it seems that the itunes api does not provide the version code and android AppUpdateInfo interface does not have access to available version name. So I'm guessing there is not much this plugin can do to work around this.

**Comment by robingenz** [comment]
> After doing some digging in the plugin source (as a complete noob of java and swift) it seems that the itunes api does not provide the version code and android AppUpdateInfo interface does not have access to available version name. So I'm guessing there is not much this plugin can do to work around this.

Yes, unfortunately this is not supported. For this reason, I am closing this issue.
