### ISSUE TITLE
bug: Reading file from a public directory throws an error

### ISSUE THREAD

**Issue by playaz87** [capawesome-team/capacitor-plugins#118]
### Plugin(s)

- [ ] Android Foreground Service
- [ ] Android Battery Optimization
- [ ] App Update
- [ ] Background Task
- [ ] Badge
- [ ] Cloudinary
- [ ] Datetime Picker
- [ ] File Compressor
- [ ] File Opener
- [X] File Picker
- [ ] Managed Configurations
- [ ] NFC
- [ ] Photo Editor
- [ ] Screen Orientation

### Version

5.2.0

### Platform(s)

- [X] Android
- [ ] iOS
- [ ] Web

### Current behavior

Picking a file from the downloads folder throws an error: 

`Error: com.samsung.android.providers.media has no access to content://media/external_primary/file/1000007011`

Code: 
```

    const res = await FilePicker.pickFiles({
      types: ['application/json'],
      multiple: false,
      readData: true,
    });
```

### Expected behavior

Read the file

### Reproduction

https://github.com/capawesome-team/capacitor-plugins/tree/main/packages/file-picker

### Steps to reproduce

Call `pickFiles()`
Select downloads directory
Select file

### Capacitor doctor

Latest Dependencies:

  @capacitor/cli: 5.6.0
  @capacitor/core: 5.6.0
  @capacitor/android: 5.6.0
  @capacitor/ios: 5.6.0

Installed Dependencies:

  @capacitor/cli: 5.3.0
  @capacitor/android: 5.5.1
  @capacitor/core: 5.5.1
  @capacitor/ios: 5.5.1

[success] iOS looking great! 👌
[success] Android looking great! 👌

### Before submitting

- [X] I have read and followed the [bug report guidelines](https://capawesome.io/contributing/bug-reports/).
- [X] I have attached links to possibly related issues and discussions.
- [X] I understand that incomplete issues (e.g. without reproduction) are closed.

**Comment by robingenz** [comment]
Which device and Android version do you use?

**Comment by playaz87** [comment]
Android 13 - Galaxy S22u

**Comment by stephan-fischer** [comment]
@playaz87  have you added following rights in your AndroidManifest.xml?

```ts
<uses-permission android:name="android.permission.READ_MEDIA_IMAGES"/>
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
```

i dont know if they needed, but i think it have to.

**Comment by playaz87** [comment]
I didn't have:

`<uses-permission android:name="android.permission.READ_MEDIA_IMAGES"/>`

But adding it made no difference

**Comment by robingenz** [comment]
@playaz87 I cannot reproduce your issue in my [demo app](https://github.com/robingenz/capacitor-plugin-demo). At least with my test device (Pixel 6a, Android 13). Feel free to debug it locally and create a PR.

https://github.com/capawesome-team/capacitor-plugins/assets/13857929/7dd18c03-5931-459f-8b50-ec3133126201

**Comment by playaz87** [comment]
It seems to be an issue with my device. I am experiencing similar issues in other apps. Feel free to close this issue. If I find a solution I will update here.
