### ISSUE TITLE
bug(nfc): It is not working in IOS

### ISSUE THREAD

**Issue by dev-ashokmanjhu** [capawesome-team/capacitor-plugins#123]
**Plugin version:**
"@capawesome-team/capacitor-nfc": "^5.0.2",

**Platform(s):**
IOS

**Current behavior:**
NOT Functioning

**Expected behavior:**
Need to scan NFC Tag

**Related code:**
```ts 
const scanNfcTag = async () => {
    console.log("first");
    try {
      await nfcInit();
      if (isNfcSupported && isNfcEnabled) {
        const data = await read();
        console.log("data", data);
        setNfcResults(JSON.stringify(data));
        dispatch({
          type: ActionType.UPDATE_SCANNED_NFC_DATA,
          payload: JSON.stringify(data),
        });
      } else {
        present(
          "Something Went Wrong. Please check NFC settings in your device.",
          TOAST_TIMER
        );
      }
    } catch (error) {
      console.log(error);
      present("Something Went Wrong", TOAST_TIMER);
    }
  };

 import { Nfc, NfcUtils, NfcTagTechType } from "@capawesome-team/capacitor-nfc"; 
 export const read = async () => {
  console.log("In Reading the nfc tag function");
  return new Promise((resolve: any) => {
    Nfc.addListener("nfcTagScanned", async (event) => {
      console.log("🚀 ~ Nfc.addListener ~ event:", JSON.stringify(event));
      await Nfc.stopScanSession();
      resolve(event.nfcTag);
    });
    Nfc.addListener("scanSessionError", async (event) => {
      console.log(
        "🚀 ~ Nfc.addListener ~ event: scanSessionError",
        JSON.stringify(event)
      );
    });
    Nfc.startScanSession();
  });
};
```

I have used your NFC plugin in my Ionic React App. It works fine on Android, but on iOS, it is not functioning. The scan alert popup, 'Ready to scan,' appears on iOS, but it doesn't actually scan anything; it remains the same. Additionally, on one device, it gives an error called 'Could not connect to tag.'

Please share code snippets for reading NFC tags in an Ionic React app if possible.

**Comment by luisbahamonde** [comment]
It gives me random errors, I can't get it to work on iOS. I have added the capability in Identifiers.

45[NFCHardwareManager areFeaturesSupported:outError:]:166 XPC Error: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named com.apple.nfcd.service.corenfc was invalidated from this process." UserInfo={NSDebugDescription=The connection to service named com.apple.nfcd.service.corenfc was invalidated from this process.}

45[NFCHardwareManager areFeaturesSupported:outError:]:166 XPC Error: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named com.apple.nfcd.service.corenfc was invalidated: failed at lookup with error 159 - Sandbox restriction." UserInfo={NSDebugDescription=The connection to service named com.apple.nfcd.service.corenfc was invalidated: failed at lookup with error 159 - Sandbox restriction.}
