### ISSUE TITLE
bug: App Update Android - API level 33 getPackageInfo(String, int) deprecated

### ISSUE THREAD

**Issue by co-dax** [capawesome-team/capacitor-plugins#131]
### Plugin(s)

- [ ] Android Foreground Service
- [ ] Android Battery Optimization
- [ ] App Update
- [ ] Background Task
- [ ] Badge
- [ ] Cloudinary
- [ ] Datetime Picker
- [ ] File Compressor
- [ ] File Opener
- [ ] File Picker
- [ ] Managed Configurations
- [ ] NFC
- [ ] Photo Editor
- [ ] Printer
- [ ] Screen Orientation

### Version

5.0.1

### Platform(s)

- [ ] Android
- [ ] iOS
- [ ] Web

### Current behavior

@robingenz - I noticed `getPackageInfo(packageName, 0);`  form the [this ](https://github.com/capawesome-team/capacitor-plugins/blob/757b673019e45b0f59c9b8a1964d0b24e0270492/packages/app-update/android/src/main/java/io/capawesome/capacitorjs/plugins/appupdate/AppUpdatePlugin.java#L230)line of code `return this.getContext().getPackageManager().getPackageInfo(packageName, 0);` has to been updated to reflect deprecation note for API 33 as per this SO issue [https://stackoverflow.com/questions/73388061/android-13-sdk-33-packagemanager-getpackageinfostring-int-deprecated-what](https://stackoverflow.com/questions/73388061/android-13-sdk-33-packagemanager-getpackageinfostring-int-deprecated-what).

Am I missing something?

Thanks.

### Expected behavior

...

### Reproduction

 ...

### Steps to reproduce

 ...

### Other information

 ...

### Capacitor doctor

 ...

### Before submitting

- [X] I have read and followed the [bug report guidelines](https://capawesome.io/contributing/bug-reports/).
- [X] I have attached links to possibly related issues and discussions.
- [X] I understand that incomplete issues (e.g. without reproduction) are closed.

**Comment by co-dax** [comment]
I made the change but how can I can test Android plugin code within Android Studio like hitting a breakpoint. I don't have experience with Capacitor plugin development.

Thanks!

**Comment by robingenz** [comment]
Take a look at the Capacitor and Android Studio docs:
- https://capacitorjs.com/docs/plugins/tutorial/android-implementation
- https://developer.android.com/studio/debug

**Comment by co-dax** [comment]
Thanks @robingenz.

I made the change, tested it on a physical Anroid API level < 33 and it works but I got the error  `failed to bind to the service` when trying to test on API 33 on emulator which is a known issue. I don't have an API > 33 Android physical device. What would be your suggestion, how do we test it? Do you perhaps have an Android api level >= 33?

**Comment by robingenz** [comment]
Feel free to create a PR. I will then take a look at it.

**Comment by co-dax** [comment]
I have created a [pull request](https://github.com/capawesome-team/capacitor-plugins/pull/134). Let me know please.
