### ISSUE TITLE
bug: FilePicker.pickFiles Android 14

### ISSUE THREAD

**Issue by mrsamse** [capawesome-team/capacitor-plugins#138]
### Plugin(s)

- [ ] Android Foreground Service
- [ ] Android Battery Optimization
- [ ] App Update
- [ ] Background Task
- [ ] Badge
- [ ] Cloudinary
- [ ] Datetime Picker
- [ ] File Compressor
- [ ] File Opener
- [X] File Picker
- [ ] Managed Configurations
- [ ] NFC
- [ ] Photo Editor
- [ ] Printer
- [ ] Screen Orientation

### Version

5.3.0

### Platform(s)

- [X] Android
- [ ] iOS
- [ ] Web

### Current behavior

I have an Ionic project with capacitor. Now I'm trying out this code:

```js
const result = await FilePicker.pickFiles({
  types: ["image/png", "image/jpeg", "application/pdf"],
  multiple: false,
  readData: false,
});
```

The UI for selecting the file opens without any problems. But when I select the file, nothing happens.
I always get this error message in the Google developer tools, when I try to debug it:
![image](https://github.com/capawesome-team/capacitor-plugins/assets/20925205/536f22bd-fb9a-4521-a791-294dd22c21bc)

The file picker works perfectly fine on iOS and in the web. Just the android implementation has this behaviour.

This are the permissions I have set in the app. Maybe I'm missing something?
![image](https://github.com/capawesome-team/capacitor-plugins/assets/20925205/69f7fab5-7472-4f89-9cc9-0bd2e6fe6462)

The permissions are also set correctly when I look at the app info. The app should be able to access the files.

I'm heavily assuming it's a configuration issue and not a bug in the plugin and would be happy if someone could point me in the right direction as to what the problem might be.

### Expected behavior

The file should be selected

### Reproduction

[nothing provided]

### Steps to reproduce

I didn't prove anything to reproduce, because I think it's not a bug in the plugin but a missconfiguration.

### Other information

Im trying this out in Samsung Galaxy S21 with Android version 14.

### Capacitor doctor

Latest Dependencies:

  @capacitor/cli: 5.7.0
  @capacitor/core: 5.7.0
  @capacitor/android: 5.7.0
  @capacitor/ios: 5.7.0

Installed Dependencies:

  @capacitor/cli: 5.6.0
  @capacitor/android: 5.6.0
  @capacitor/core: 5.6.0
  @capacitor/ios: 5.6.0

[success] iOS looking great! 👌
[success] Android looking great! 👌

### Before submitting

- [X] I have read and followed the [bug report guidelines](https://capawesome.io/contributing/bug-reports/).
- [X] I have attached links to possibly related issues and discussions.
- [X] I understand that incomplete issues (e.g. without reproduction) are closed.

**Comment by mrsamse** [comment]
Well i tried the [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) out and it worked there with my phone. I close this Issue and ask in the "Discussions" if anyone has a hint.

**Comment by robingenz** [comment]
See https://github.com/capawesome-team/capacitor-plugins/discussions/139#discussioncomment-8411089
