### ISSUE TITLE
feat: Create a getAlbumMedias() feature to get an array of medias and their path

### ISSUE THREAD

**Issue by maximilien0405** [capawesome-team/capacitor-plugins#143]
### Plugin(s)
- [X] File Picker

### Current problem

Currently there is no way to pick an album of medias (images/videos). This is a big problem because it limits the possibility to get medias only though the native IOS/Android popup.

### Preferred solution

With a `.getAlbums()` function, we could get an array of albums in the gallery, to get their ID and name, and display it in the front-end side.

With a `.getAlbumMedias(albumId: string)` function we could get all of the medias inside of an album, by example the recent album. With some parameters like `limit: number` or `start: number` and `stop: number`. This would allow us to display the medias in our app an create our own way to get medias. Just like every social media app out there. To get the images in an instant, an option to disable the transcoding and get the direct path to the media (to display it in a gallery type component)

**Comment by robingenz** [comment]
The purpose of the file picker plugin is to allow the user to select one or more files. Your request is not in the scope of the plugin. I will therefore close this issue.

However, have you already looked at the [Capacitor Media](https://github.com/capacitor-community/media) plugin? Your request should fit better to this plugin.

**Comment by stephan-fischer** [comment]
@robingenz Feature Requests in Capacitor Media does take a very very long time...
