### ISSUE TITLE
Different path from pickImages method 

### ISSUE THREAD

**Issue by DmitryRazhkou** [capawesome-team/capacitor-plugins#145]
### Plugin(s)

- [ ] Android Foreground Service
- [ ] Android Battery Optimization
- [ ] App Update
- [ ] Background Task
- [ ] Badge
- [ ] Cloudinary
- [ ] Datetime Picker
- [ ] File Compressor
- [ ] File Opener
- [X] File Picker
- [ ] Managed Configurations
- [ ] NFC
- [ ] Photo Editor
- [ ] Printer
- [ ] Screen Orientation

### Version

5.3.0

### Platform(s)

- [X] Android
- [ ] iOS
- [ ] Web

### Current behavior

When using FilePicker.pickImages on different Android devices (10 and 13), the path of the uploaded image varies:

Android 10: content://media/external/images/media/324793
Android 13: content://com.miui.gallery.open/raw/%2Fstorage%2Femulated%2F0%2FDCIM%2FScreenshots%2FScreenshot_2024-02-17-13-02-06-116_ge.qwerty.credo.jpg
Because of this difference, it's not possible to access the file from the device's file system using the path content://media/external/images/media/324793. Currently, I'm using @capacitor/filesystem for this purpose, and with the path from Android 13, everything works well.

### Expected behavior

Get the path like on Android 13 on all devices.

### Reproduction

.

### Steps to reproduce

.

### Capacitor doctor

.

### Before submitting

- [X] I have read and followed the [bug report guidelines](https://capawesome.io/contributing/bug-reports/).
- [X] I have attached links to possibly related issues and discussions.
- [X] I understand that incomplete issues (e.g. without reproduction) are closed.

**Comment by robingenz** [comment]
This path is provided by Android. The plugin has no control over this and does not distinguish between Android versions. For this reason, I am closing this issue.
