### ISSUE TITLE
Native update app

### ISSUE THREAD

**Issue by grzegorzCieslik95** [capawesome-team/capacitor-plugins#153]
### Plugin(s)

- [ ] Android Foreground Service
- [ ] Android Battery Optimization
- [ ] App Update
- [ ] Background Task
- [ ] Badge
- [ ] Cloudinary
- [ ] Datetime Picker
- [ ] File Compressor
- [ ] File Opener
- [ ] File Picker
- [ ] Managed Configurations
- [ ] NFC
- [ ] Photo Editor
- [ ] Printer
- [ ] Screen Orientation

### Current problem

Do you know any library which can do sth like on the screen?
![Screenshot_20240308_192806_Google Play Store](https://github.com/capawesome-team/capacitor-plugins/assets/22835944/bce2d28e-c8ff-4354-8040-e6fa80b1742a)

### Preferred solution

Update app on iOS and Android 

### Before submitting

- [X] I have read and followed the [feature request guidelines](https://capawesome.io/contributing/feature-requests/).
- [X] I have attached links to possibly related issues and discussions.

**Comment by robingenz** [comment]
This feature is called "In-app update" and is only available on Android. You can use this plugin: https://capawesome.io/plugins/app-update/
