### ISSUE TITLE
feat(nfc): Implementation of HCE

### ISSUE THREAD

**Issue by Droppix** [capawesome-team/capacitor-plugins#155]
### Plugin(s)

- [ ] Android Foreground Service
- [ ] Android Battery Optimization
- [ ] App Update
- [ ] Background Task
- [ ] Badge
- [ ] Cloudinary
- [ ] Datetime Picker
- [ ] File Compressor
- [ ] File Opener
- [ ] File Picker
- [ ] Managed Configurations
- [X] NFC
- [ ] Photo Editor
- [ ] Printer
- [ ] Screen Orientation

### Current problem

HCE (Android) is not yet supported. 
May be iOS (soon...)

### Preferred solution

I'd like to trigger an action between 2 devices (Android for now, iOS later if Apple really decides to open it up, it's already in the works...) via the HCE.

### Alternative options

None

### Additional context

None

### Before submitting

- [X] I have read and followed the [feature request guidelines](https://capawesome.io/contributing/feature-requests/).
- [X] I have attached links to possibly related issues and discussions.

**Comment by alexcroox** [comment]
I'd love HCE so I add "unlock smart padlock" functionality to my capacitor app (the smartlock uses NFC cards to unlock itself and I'd like the phone/app to emulate one of those cards)

**Comment by robingenz** [comment]
@alexcroox I worked on an implementation some time ago but never had a real use case to test it. Would you be willing to test the implementation if I finish it?

**Comment by alexcroox** [comment]
Yeah I’d love to. Am I right in saying it’s Android only? Just waiting for the padlock to arrive in the next couple of weeks from the US

**Comment by robingenz** [comment]
@alexcroox Yes, it's Android only. :/ Great, I'll get back to you as soon as it's ready.

**Comment by robingenz** [comment]
I've just published a dev version for testing:

```
npm i @capawesome-team/capacitor-nfc@6.2.0-dev.0df6725.1718009611
```

You need to register a new Android service, see [Services](https://github.com/capawesome-team/sponsorware/pkgs/npm/capacitor-nfc/227751232#services).

After that, you can use the following new methods:

- `respond(...)`
- `addListener('commandReceived', ...)`
- `addListener('nfcLinkDeactivated', ...)`

Here is an example:

```ts
import { Nfc } from '@capawesome-team/capacitor-nfc';

const addListener = async () => {
  Nfc.addListener('commandReceived', async (event) => {
    console.log(event.data);
	await Nfc.respond({ data: [...] });
  });
};
```

Take a look at the [API](https://github.com/capawesome-team/sponsorware/pkgs/npm/capacitor-nfc/227751232#api) for more information.

I look forward to any feedback. 🙌

**Comment by thangman22** [comment]
@robingenz How can I access this version?

**Comment by robingenz** [comment]
@thangman22 Just install the dev version i mentioned above:

``
npm i @capawesome-team/capacitor-nfc@6.2.0-dev.0df6725.1718009611
```

**Comment by robingenz** [comment]
@thangman22 You are using the public npm registry. You need to use the private GitHub registry. Please make sure to follow the [installation instructions](https://capawesome.io/sponsors/insiders/getting-started/?plugin=capacitor-nfc). If you have any more questions, please reach out via email [supportcapawesome.io](mailto:supportcapawesome.io).

**Comment by thangman22** [comment]
@robingenz Can you provide a full example for emulate the text record?

**Comment by robingenz** [comment]
@thangman22 I assume you are referring to an NDEF record. This is not so straightforward, as the Android HCE implementation does not directly support the NDEF format but communicates so-called APDU commands. That's why I do not have an example available right now.

**Comment by robingenz** [comment]
Has anyone had a chance to test it?

@alexcroox Did it work for you?

**Comment by alexcroox** [comment]
@robingenz you wouldn't believe it but I'm _still_ waiting for the US company to ship the padlock to me here in the UK, they've had bad supply chain issues. https://www.digitalkeys.io/5g-iot-smart-padlock

**Comment by robingenz** [comment]
@alexcroox Oh dear, all right. 😆 Thanks for the quick reponse.
