### ISSUE TITLE
feat(file-picker): add `pickDirectory(...)` method

### ISSUE THREAD

**Issue by ieugen** [capawesome-team/capacitor-plugins#16]
I would like to be able to pick a directory instead of a file.

I'm working on adding Android local storage support for organice https://github.com/200ok-ch/organice/ . 
We need the ability to select the directory that contains the org files to manage.

Thanks,
Eugen

**Comment by Nikita-schetko** [comment]
Guys, is there any chance that 'open directory' feature will be added for file picker ? Would be extremely nice to have

**Comment by robingenz** [comment]
@Nikita-schetko Yes, but there is no ETA. PRs are welcome.

**Comment by maximilien0405** [comment]
Yes this would be a crazy useful feature ! This would allow us to create our own way of picking images, like in every social media app theses days. Is there any other Capacitor package that does that BTW ? I've searched a lot and found nothing.. @robingenz
