### ISSUE TITLE
feat: Support For cordova-plugin-mfp to capacitor-mfp

### ISSUE THREAD

**Issue by danaabhi** [capawesome-team/capacitor-plugins#162]
### Name

cordova-plugin-mfp to capacitor-mfp

### Platform(s)

- [X] Android
- [X] iOS
- [X] Web

### Description

Dear Team, 

As a growing market demand people need mfp plugin to support in capacitor, but till mfp 8.0 there is no support for capacitor, is there anything that we can create a new plugin that will be same as cordova mfp plugin but in capacitor.

### Before submitting

- [X] I have read and followed the [plugin request guidelines](https://capawesome.io/contributing/plugin-requests/).
- [X] I have attached links to possibly related issues and discussions.

**Comment by danaabhi** [comment]
@robingenz  please find the link to plugin 
https://mobilefirstplatform.ibmcloud.com/tutorials/it/foundation/8.0/application-development/sdk/cordova/

**Comment by robingenz** [comment]
Thank you for the link. Unfortunately, we are currently not planning to create a Capacitor plugin for this SDK. Therefore, I am closing this issue.
