### ISSUE TITLE
feat: filepicker README outdated

### ISSUE THREAD

**Issue by boldtrn** [capawesome-team/capacitor-plugins#163]
### Plugin(s)

- [ ] Android Foreground Service
- [ ] Android Battery Optimization
- [ ] App Update
- [ ] Background Task
- [ ] Badge
- [ ] Cloudinary
- [ ] Datetime Picker
- [ ] File Compressor
- [ ] File Opener
- [X] File Picker
- [ ] Managed Configurations
- [ ] NFC
- [ ] Photo Editor
- [ ] Printer
- [ ] Screen Orientation

### Current problem

The README contains multiple instead of limit

https://github.com/capawesome-team/capacitor-plugins/blob/main/packages/file-picker/README.md
see: https://github.com/capawesome-team/capacitor-plugins/pull/148

### Preferred solution

be updated :)

### Before submitting

- [X] I have read and followed the [feature request guidelines](https://capawesome.io/contributing/feature-requests/).
- [X] I have attached links to possibly related issues and discussions.

**Comment by robingenz** [comment]
Thank you!
