### ISSUE TITLE
bug: @capawesome/capacitor-file-picker `pickFiles()` function not returning `file.blob` in android works fine in browser.

### ISSUE THREAD

**Issue by Saqib92** [capawesome-team/capacitor-plugins#167]
### Plugin(s)

- [ ] Android Foreground Service
- [ ] Android Battery Optimization
- [ ] App Update
- [ ] Background Task
- [ ] Badge
- [ ] Cloudinary
- [ ] Datetime Picker
- [ ] File Compressor
- [ ] File Opener
- [X] File Picker
- [ ] Managed Configurations
- [ ] NFC
- [ ] Photo Editor
- [ ] Printer
- [ ] Screen Orientation

### Version

5.1.1

### Platform(s)

- [X] Android
- [ ] iOS
- [ ] Web

### Current behavior

`pickFiles()` function not returning `file.blob` in android but return `file.blob` in browser.

### Expected behavior

it should return `file.blob` in android to i can create file and upload it to server:

My code:

```
const result = await FilePicker.pickFiles();
const file:any = result.files[0];
console.log(file); // can see file.blob in browser

    const formData = new FormData();
    if (file.blob) {
      const rawFile = new File([file.blob], file.name, {
        type: file.mimeType,
      });
      console.log(rawFile) // consoles in browser not in android havn't checked on ios yet. 
      formData.append('file', rawFile, file.name);
    }
```

console result from android app:

```
[
    {
        "duration": 5,
        "height": 1438,
        "width": 720,
        "mimeType": "video/mp4",
        "modifiedAt": 1713882112000,
        "name": "04_23_2024_072146.mp4",
        "path": "content://com.android.providers.media.documents/document/video%3A1000029462",
        "size": 649971
    }
]
```

console result from browser:

```
[
    {
        "blob": {
            lastModified: 1635348618000,
            lastModifiedDate: Wed Oct 27 2021 20:30:18 GMT+0500 (Pakistan Standard Time) {},
            name: "big buck bunny 720p 2mb.mp4",
            size: 2107842,
            type: "video/mp4",
            webkitRelativePath: ""
        },
        "modifiedAt": 1635348618000,
        "mimeType": "video/mp4",
        "name": "big buck bunny 720p 2mb.mp4",
        "size": 2107842
    }
]
```

### Reproduction

https://github.com/Saqib92/capacitor-screen-recording

### Steps to reproduce

1: install plugin version @5.1.1
2: use pickFiles() method

### Capacitor doctor

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 6.0.0
  @capacitor/core: 6.0.0
  @capacitor/android: 6.0.0
  @capacitor/ios: 6.0.0

Installed Dependencies:

  @capacitor/core: 5.4.2
  @capacitor/cli: 5.0.4
  @capacitor/android: 5.0.4
  @capacitor/ios: 5.0.4
```

### Before submitting

- [X] I have read and followed the [bug report guidelines](https://capawesome.io/contributing/bug-reports/).
- [X] I have attached links to possibly related issues and discussions.
- [X] I understand that incomplete issues (e.g. without reproduction) are closed.

**Comment by robingenz** [comment]
From the [docs](https://capawesome.io/plugins/file-picker/):

> The Base64 string representation of the data contained in the file. Is only provided if `readData` is set to `true`.

**Comment by Saqib92** [comment]
> From the [docs](https://capawesome.io/plugins/file-picker/):
> 
> > The Base64 string representation of the data contained in the file. Is only provided if `readData` is set to `true`.

But my server accepts File object. is there a way i can get file object as mentioned in the plugin example.
or i have to convert it my self before uploading?

**Comment by robingenz** [comment]
If you want to use blob, you can simply [read the file](https://capawesome.io/blog/the-file-handling-guide-for-capacitor/#read-a-file) using the `fetch` API and then build a file object (see [Usage](https://capawesome.io/plugins/file-picker/#usage) section):

```ts
import { Capacitor } from '@capacitor/core';
import { FilePicker } from '@capawesome/capacitor-file-picker';

const appendFileToFormData = async () => {
  const result = await FilePicker.pickFiles();
  const file = result.files[0];

  let blob;
  if (file.blob) {
    blob = file.blob;
  } else {
    const webPath = Capacitor.convertFileSrc(file.path);
    const response = await fetch(webPath);
    blob = await response.blob();
  }
  const formData = new FormData();
  const rawFile = new File(file.blob, file.name, {
    type: file.mimeType,
  });
  formData.append('file', rawFile, file.name);
};
```

**Comment by anusha-kaparapu** [comment]
Thanks @robingenz, i tried this way but i did not get the blob value, please see the below code once. Please let me know  anything i missed here.

```
pickMedia = async () => {
      const result = await FilePicker.pickImages({
        multiple: true
      });
      this.images = result?.files;
   
      console.log('pick-images::::', this.images);
      this.images.forEach(async (data) => {
        console.log('path::::::', data?.path); // get log path:::::: file:///var/mobile/Containers/Data/Application/82418282-5158-4E2A-860E-C44B17895FAA/Library/Caches/IMG_5772.png
        const webPath = Capacitor.convertFileSrc(data?.path);
        console.log('webPath::::::', webPath) // webPath:::::: capacitor://localhost:8080/_capacitor_file_/var/mobile/Containers/Data/Application/82418282-5158-4E2A-860E-C44B17895FAA/Library/Caches/IMG_5772.png
        const response = await fetch(webPath);
        console.log('response=====>', response) // getting empty response
        let blob = await response?.blob();
        console.log('blob::::', blob); // getting empty blob
   });
}
```

**Comment by Saqib92** [comment]
@anusha-kaparapu check this and amened as per your requirments.

```
pickMedia = async () => {
  const result = await FilePicker.pickImages({
    multiple: true
  });
  this.images = result?.files;

  this.images.forEach(async (data) => {

    let blob;
    if (data.blob) {
      blob = data.blob;
    } else {
      const webPath = Capacitor.convertFileSrc(data.path);
      const response = await fetch(webPath);
      blob = await response.blob();
    }

    const rawFile = new File([data.blob], data.name, {
      type: data.mimeType,
    });
    console.log(rawFile);
    this.rawFilesArray.push(rawFile); //use this as per your requirments
  });
}
```

**Comment by anusha-kaparapu** [comment]
> @anusha-kaparapu check this and amened as per your requirments.
> 
> ```
> pickMedia = async () => {
>   const result = await FilePicker.pickImages({
>     multiple: true
>   });
>   this.images = result?.files;
> 
>   this.images.forEach(async (data) => {
> 
>     let blob;
>     if (data.blob) {
>       blob = data.blob;
>     } else {
>       const webPath = Capacitor.convertFileSrc(data.path);
>       const response = await fetch(webPath);
>       blob = await response.blob();
>     }
> 
>     const rawFile = new File([data.blob], data.name, {
>       type: data.mimeType,
>     });
>     console.log(rawFile);
>     this.rawFilesArray.push(rawFile); //use this as per your requirments
>   });
> }
> ```

Hi @Saqib92 , may i know your capacitor-file-picker and capacitor version, mine is "@capawesome/capacitor-file-picker": "^0.6.3" and capacitor v4.
Can you please provide your response while using below methods
Capacitor.convertFileSrc(data.path)
const response = await fetch(webPath);

Our log response.
```
 const webPath = Capacitor.convertFileSrc(data?.path);
        console.log('webPath::::::', webPath) // get log webPath:::::: capacitor://localhost:8080/_capacitor_file_/var/mobile/Containers/Data/Application/82418282-5158-4E2A-860E-C44B17895FAA/Library/Caches/IMG_5772.png
        const response = await fetch(webPath);
        console.log('response=====>', response) // getting empty response {}
        let blob = await response?.blob();
        console.log('blob::::', blob); // getting empty blob {}
```
