### ISSUE TITLE
feat(file-picker): Create the option to define a limit for the number of files picked by user

### ISSUE THREAD

**Issue by levymeireles** [capawesome-team/capacitor-plugins#17]
**Is your feature request related to a problem? Please describe:**

I would like if can define a max number of files picked by user, for delimite (how like whatsapp). This would prevent the user from choosing infinite files.

**Describe the solution you'd like:**

Just an argumento in options the file picker for limit this.
like: limit?: 10 (the user can upload 10 files).

**Describe alternatives you've considered:**

**Additional context:**

**Comment by stephan-fischer** [comment]
@robingenz do you know, when this feature will be integrated?

**Comment by robingenz** [comment]
No, there is no ETA. I'm not even sure if it's possible to set a limit on Android or iOS. Feel free to create a PR.

**Comment by stephan-fischer** [comment]
@robingenz  It's easily possible to create for ios a limit.  [selectionLimit](https://developer.apple.com/documentation/photokit/phpickerconfiguration/3606592-selectionlimit)
But for Android its not easy... 
Would a pull request for ios be enough?

**Comment by robingenz** [comment]
Yes, this would be enough. It seems like it's not supported on Android and Web.

**Comment by stephan-fischer** [comment]
Right, but for Android 13+ following new api exists: [Photo Picker](https://developer.android.com/training/data-storage/shared/photopicker)

But I think that would be a major change!

**Comment by robingenz** [comment]
Oh, that's great! Thanks for sharing! 

> But I think that would be a major change!

Yes, i will publish that with the next major release (Capacitor 6).
