### ISSUE TITLE
bug: Zip plugin doesn't work properly

### ISSUE THREAD

**Issue by loremru** [capawesome-team/capacitor-plugins#176]
### Plugin(s)

- [ ] Android Foreground Service
- [ ] Android Battery Optimization
- [ ] App Update
- [ ] Background Task
- [ ] Badge
- [ ] Cloudinary
- [ ] Datetime Picker
- [ ] File Compressor
- [ ] File Opener
- [ ] File Picker
- [ ] Managed Configurations
- [ ] NFC
- [ ] Photo Editor
- [ ] Printer
- [ ] Screen Orientation
- [X] Zip

### Version

6.0.0

### Platform(s)

- [X] Android
- [X] iOS
- [ ] Web

### Current behavior

not full unpacking, just part of archieve and there is no error

### Expected behavior

upack all zip

### Reproduction

code below

### Steps to reproduce
```

import { Directory, Filesystem } from '@capacitor/filesystem'
import { Zip } from '@capawesome-team/capacitor-zip'

export async function downloadRegion() {
  const r = await Filesystem.downloadFile({
    url: 'https://storage.yandexcloud.net/gunza-maps/satellite/85.zip',
    directory: Directory.Library,
    path: '/satellite.zip',
    progress: true,
  })

  try {
    await Filesystem.requestPermissions()
    console.log((await Filesystem.stat({ directory: Directory.Library, path: 'satellite.zip' })).size)
    await Zip.unzip({
      source: r.path as string,
      destination: (await Filesystem.getUri({ path: 'satellite', directory: Directory.Library })).uri,
    })
    console.log('FILES0', await Filesystem.readdir({ directory: Directory.Library, path: 'satellite' }))
    console.log((await Filesystem.stat({ directory: Directory.Library, path: 'satellite' })).size)
  } catch (e) {
    console.log('ERR: ', e)
  }
}
```

### Other information

<img width="912" alt="image" src="https://github.com/capawesome-team/capacitor-plugins/assets/66596500/e3a6460b-03fa-4140-b642-adcf56196389">

24576 bytes of 10515726 bytes

[85.zip](https://github.com/capawesome-team/capacitor-plugins/files/15253768/85.zip)

### Capacitor doctor

💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 6.0.0
  @capacitor/core: 6.0.0
  @capacitor/android: 6.0.0
  @capacitor/ios: 6.0.0

Installed Dependencies:

  @capacitor/cli: 6.0.0
  @capacitor/core: 6.0.0
  @capacitor/android: 6.0.0
  @capacitor/ios: 6.0.0

[success] iOS looking great! 👌
[success] Android looking great! 👌

### Before submitting

- [X] I have read and followed the [bug report guidelines](https://capawesome.io/contributing/bug-reports/).
- [X] I have attached links to possibly related issues and discussions.
- [X] I understand that incomplete issues (e.g. without reproduction) are closed.

**Comment by robingenz** [comment]
Thank you for your request. The plugin is quite new and not yet heavily tested. I will take a look tomorrow and get back to you. Please attach the zip file to this GitHub issue.

**Comment by loremru** [comment]
@robingenz 

You can get it from
https://storage.yandexcloud.net/gunza-maps/satellite/85.zip

or download it direct to device through FIlesystem.downloadFile like I did

**Comment by robingenz** [comment]
I've just tested it and it worked without issues. I used the following code for testing:

```ts
  public async unzip(): Promise<void> {
	// Download the file
    const { path } = await Filesystem.downloadFile({
      url: 'https://storage.yandexcloud.net/gunza-maps/satellite/85.zip',
      directory: Directory.Library,
      path: 'satellite.zip',
    });
    if (!path) {
      return;
    }
    // Create the destination directory
    const directoryName = `${Date.now().toString()}`;
    await Filesystem.mkdir({
      path: directoryName,
      directory: Directory.Library,
      recursive: true,
    });
    const { uri: destinationUri } = await Filesystem.getUri({
      path: directoryName,
      directory: Directory.Library,
    });
    // Unzip the file
    await Zip.unzip({
      source: path,
      destination: destinationUri,
    });
    // List the files in the destination directory
    await Filesystem.readdir({
      path: destinationUri,
    });
  }
```

![grafik](https://github.com/capawesome-team/capacitor-plugins/assets/13857929/33836d4e-b61c-4f1b-a9a0-240f17748c62)
