### ISSUE TITLE
feat: get NFC Antenna Location

### ISSUE THREAD

**Issue by entwicklung-sanacorp** [capawesome-team/capacitor-plugins#179]
### Plugin(s)

- [ ] Android Foreground Service
- [ ] Android Battery Optimization
- [ ] App Update
- [ ] Background Task
- [ ] Badge
- [ ] Cloudinary
- [ ] Datetime Picker
- [ ] File Compressor
- [ ] File Opener
- [ ] File Picker
- [ ] Managed Configurations
- [X] NFC
- [ ] Photo Editor
- [ ] Printer
- [ ] Screen Orientation
- [ ] Zip

### Current problem

We would like to help our users scan the NFC chips by providing visual indicator where the NFC Antenna location is on the device.

### Preferred solution

On new Android devices there is an API method to get the location https://developer.android.com/reference/android/nfc/NfcAdapter#getNfcAntennaInfo()

Can you include this feature in your NFC Plugin?

We are not aware of such an API on other devices but would be grateful if you find a way to get NFC Antenna location there as well.

### Before submitting

- [X] I have read and followed the [feature request guidelines](https://capawesome.io/contributing/feature-requests/).
- [X] I have attached links to possibly related issues and discussions.

**Comment by robingenz** [comment]
Sure, i will work on this next week.

**Comment by robingenz** [comment]
I've just published a dev version for testing:

```
npm i @capawesome-team/capacitor-nfc@6.0.0-dev.58f1c62.1715626586
```

A new `getAntennaInfo` method was added. Please let me know if it works as expected.

**Comment by entwicklung-sanacorp** [comment]
Thank you for the quick implementations. It works perfectly.
