### ISSUE TITLE
feat(live-update): support delta updates

### ISSUE THREAD

**Issue by robingenz** [capawesome-team/capacitor-plugins#180]
### Discussed in https://github.com/capawesome-team/capacitor-plugins/discussions/178

<div type='discussions-op-text'>

<sup>Originally posted by **Eraldo** May 10, 2024</sup>
Concept: https://en.wikipedia.org/wiki/Delta_update

Ratio: To increase speed and decrease traffic. 🎉 

Happy to talk about different implementation strategies and use cases. 👍 </div>

**Comment by luisbytes** [comment]
Hello, is this supported for the self-hosted or manual version?

**Comment by robingenz** [comment]
@luisbytes Not yet, but I can add support if you're interested. Should be a quick win.

**Comment by luisbytes** [comment]
@robingenz This is super interesting, reviewing the source code I see that the downloadBundleOfTypeManifest method exists, it would be adding it to the downloadBundle method.

To achieve this downloadBundle should accept a new artifact-type parameter that defaults to zip.

**Comment by mustafa0x** [comment]
> @luisbytes Not yet, but I can add support if you're interested. Should be a quick win.

yes please!

**Comment by robingenz** [comment]
@mustafa0x It's already available via the latest version.

**Comment by mustafa0x** [comment]
Thanks. How to use? I didn't see anything in the docs.

**Comment by robingenz** [comment]
The [`downloadBundle()`](https://capawesome.io/plugins/live-update/#downloadbundle) method now accepts a `artifactType` property, see [DownloadBundleOptions](https://capawesome.io/plugins/live-update/#downloadbundleoptions).
