### ISSUE TITLE
bug: Live update plugin not download bundle

### ISSUE THREAD

**Issue by theKHR3b** [capawesome-team/capacitor-plugins#182]
### Plugin(s)

- [ ] Android Foreground Service
- [ ] Android Battery Optimization
- [ ] App Update
- [ ] Background Task
- [ ] Badge
- [ ] Cloudinary
- [ ] Datetime Picker
- [ ] File Compressor
- [ ] File Opener
- [ ] File Picker
- [ ] Managed Configurations
- [ ] NFC
- [ ] Photo Editor
- [ ] Printer
- [ ] Screen Orientation
- [ ] Zip

### Version

6.0.4

### Platform(s)

- [X] Android
- [ ] iOS
- [ ] Web

### Current behavior

Hello! I am trying to integrate Live update plugin into my app. But i don't know why he is not download new bundle from self hosted server. So here is my flow:
1. in app.component.ts i am call this.appUpdate.checkForUpdate(); in app-update service. (in platform.ready func)
2. then call await LiveUpdate.ready(); - for sure if last update was succesfull, stay on it.
3. then check for new version from my server, let assume the version number is "1"
4. then call download bundle, and then set bundle:
```
try {
                await LiveUpdate.downloadBundle({
                    url: environment.downloadBundleUrl, <<<---url look like this  'https://example.ru:8443/bundle.zip'
                    bundleId: version, <<<--- version we get from server e.g. "1"
                });

                await LiveUpdate.setBundle({ bundleId: version });

                console.log('new bundle ready.');
                this.updateReadyToInstall.next(true);
            } catch (error) {
                console.log('new bundle download error.', error); <<<--- new bundle download error. Error: bundle not found.
            }
```
In the chrome:inspect i see logs:

```
VM4:365 native LiveUpdate.downloadBundle (#23004534)
VM4:372 ObjectcallbackId: "23004534"methodName: "downloadBundle"options: {url: 'https://example.ru:8443/bundle.zip', bundleId: '1'}pluginId: "LiveUpdate" 
VM4:339 result LiveUpdate.downloadBundle (#23004534)
VM4:350 undefined 

VM4:365 native LiveUpdate.setBundle (#23004535)
VM4:372 ObjectcallbackId: "23004535"methodName: "setBundle"options: {bundleId: '1'}pluginId: "LiveUpdate"
VM4:339 result LiveUpdate.setBundle (#23004535)
VM4:347 {message: 'bundle not found.'}

(anonymous) @ VM4:347
returnResult @ VM4:930
win.androidBridge.onmessage @ VM4:918
main.js:691 new bundle download error. Error: bundle not found.
    at returnResult (<anonymous>:943:32)
    at win.androidBridge.onmessage (<anonymous>:918:21)
```
in logs i see that urls are corrected and functions are called.
when I just copy and paste url in safari it begin download file without problem.
file size is about 4,6Mb it is a full build of ionic app (www folder) with index.html file inside.
Phone on android version 9, wi-fi connected, internet connected: phone found version "1" on server, and other parts of application work with api.
Looking in networking tab in chrome inspect there is no download file, just api queries and some js files.
Trying to looking in logcat *:V | grep okhttp or <appName> or download but nothing interesting found.
So now I am thinking why he didn't download file? And, maybe, where i could found some information why?

### Expected behavior

Plugin just download file, or give some error with info if can't

### Reproduction

not provided

### Steps to reproduce

not provided

### Capacitor doctor

💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 6.0.0
  @capacitor/core: 6.0.0
  @capacitor/android: 6.0.0
  @capacitor/ios: 6.0.0

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/core: 6.0.0
  @capacitor/cli: 6.0.0
  @capacitor/android: 6.0.0

[success] Android looking great! 👌

### Before submitting

- [X] I have read and followed the [bug report guidelines](https://capawesome.io/contributing/bug-reports/).
- [X] I have attached links to possibly related issues and discussions.
- [X] I understand that incomplete issues (e.g. without reproduction) are closed.

**Comment by robingenz** [comment]
Please paste the logs from Logcat.

**Comment by theKHR3b** [comment]
here hte files with logs. command was: ./adb logcat '*:V' -v time -d | grep "something" > logs.txt
Restarted app four times, uses grep appname, grep liveupdate grep download and file logs without grep.
Where I find I cut real url, just paste "example.ru"

[logs grep appname.txt](https://github.com/capawesome-team/capacitor-plugins/files/15286821/logs.grep.appname.txt)
[logs grep download.txt](https://github.com/capawesome-team/capacitor-plugins/files/15286822/logs.grep.download.txt)
[logs grep LiveUpdate.txt](https://github.com/capawesome-team/capacitor-plugins/files/15286823/logs.grep.LiveUpdate.txt)
[logs.txt](https://github.com/capawesome-team/capacitor-plugins/files/15286824/logs.txt)

And forgot show my config:
```
    plugins: {
        LiveUpdate: {
            autoDeleteBundles: true,
            enabled: true,
            readyTimeout: 10000,
            resetOnUpdate: true,
        },
```

**Comment by robingenz** [comment]
I couldn't find anything in the logs. Please try debugging the plugin locally by setting breakpoints in the LiveUpdate.java file via Android Studio.

**Comment by theKHR3b** [comment]
Hello! So debugging was succesfull, and here is info: 
In file LiveUpdate.java error is in 268 line:
```
        // Move the bundle directory to the bundles directory
        File bundleDirectory = buildBundleDirectoryFor(bundleId);
        indexHtmlFile.getParentFile().renameTo(bundleDirectory);
```
in my device this method tries rename folder: /data/user/0/ru.ykdommaster.test/cache/395ce4c8-7990-4a96-a37e-9540979de41f
to folder: /data/user/0/ru.ykdommaster.test/files/_capacitor_live_update_bundles/1

You do not check return value from this method, and in my app i think thats because there no "_capacitor_live_update_bundles" folder in app data folder at all.
So additional code is to create here folder "_capacitor_live_update_bundles" with full parent folder if needed (mkdirs() method). After that return value become true and all working as expected.
```
        // Move the bundle directory to the bundles directory
        File bundlesDirectory = buildBundlesDirectory();
      if (! bundlesDirectory.exists()){ bundlesDirectory.mkdirs(); }
        File bundleDirectory = buildBundleDirectoryFor(bundleId);
        Boolean result = indexHtmlFile.getParentFile().renameTo(bundleDirectory); 
```
But maybe you will think about move this creation in constructor or somewhere else. I cant found constructor, since I am not undestand Java very well.
In additional maybe you should check on return value of renameTo method or/and maybe try-catch block because docs in studio says:

> Renames the file denoted by this abstract pathname.
> Many failures are possible. Some of the more likely failures include.
> .....
> The return value should always be checked to make sure that the rename operation was successful
Or, as docs says again:
> Note that the java.nio.file.Files class defines the move method to move or rename a file in a platform independent manner
So maybe switch to **java.nio.file.Files**. 

After all the bug is found, but i am cant fix it in proper way, just a workaround. 
And big thank you for this great plugin.

**Comment by robingenz** [comment]
I just published a dev version with a fix: 

```
npm i @capawesome/capacitor-live-update@6.0.4-dev.39b851d.1715623818
```

Let me know if it works.

**Comment by theKHR3b** [comment]
> I just published a dev version with a fix:
> 
> ```
> npm i @capawesome/capacitor-live-update@6.0.4-dev.39b851d.1715623818
> ```
> 
> Let me know if it works.

Yes, now it worked as expected.
