### ISSUE TITLE
feat: Is it possible to make unzip faster?

### ISSUE THREAD

**Issue by loremru** [capawesome-team/capacitor-plugins#186]
### Plugin(s)

- [ ] Android Foreground Service
- [ ] Android Battery Optimization
- [ ] App Update
- [ ] Background Task
- [ ] Badge
- [ ] Bluetooth Low Energy
- [ ] Cloudinary
- [ ] Datetime Picker
- [ ] File Compressor
- [ ] File Opener
- [ ] File Picker
- [ ] Live Update
- [ ] Managed Configurations
- [ ] NFC
- [ ] Photo Editor
- [ ] Printer
- [ ] Screen Orientation
- [X] Zip

### Current problem

I have an 1.5gb zip file with ±50k files. It takes 3.5min to unzip file with plugin on IOS (iphone 12). But with the native Files app it takes 1min to unzip - 3.5x faster than plugin. 
I use same directory to download and to unzip archive, so I think it's a plugin issue.

### Preferred solution

Make unzip as fast as native software.

### Additional context

`https://storage.yandexcloud.net/gunza-maps/satellite/26.zip` - my archive file

### Before submitting

- [X] I have read and followed the [feature request guidelines](https://capawesome.io/contributing/feature-requests/).
- [X] I have attached links to possibly related issues and discussions.

**Comment by robingenz** [comment]
Thank you for your request. I've just did some improvements. It should be much faster now. Here is a dev version: 

```
npm i @capawesome-team/capacitor-zip@6.1.0-dev.9911cf4.1715927091
```
