### ISSUE TITLE
bug:  setBundle success callback is never called

### ISSUE THREAD

**Issue by lightoze** [capawesome-team/capacitor-plugins#187]
### Plugin(s)

- [ ] Android Foreground Service
- [ ] Android Battery Optimization
- [ ] App Update
- [ ] Background Task
- [ ] Badge
- [ ] Bluetooth Low Energy
- [ ] Cloudinary
- [ ] Datetime Picker
- [ ] File Compressor
- [ ] File Opener
- [ ] File Picker
- [X] Live Update
- [ ] Managed Configurations
- [ ] NFC
- [ ] Photo Editor
- [ ] Printer
- [ ] Screen Orientation
- [ ] Zip

### Version

6.0.5

### Platform(s)

- [X] Android
- [X] iOS
- [ ] Web

### Current behavior

`setBundle` promise never resolves because the plugin callback is called only on error, this blocks subsequent app refresh logic from executing.

### Expected behavior

Documentation suggests `await LiveUpdate.setBundle(...)`. It is safe to skip `await` here but I would expect both ways to work correctly.

### Reproduction

-

### Steps to reproduce

```
await LiveUpdate.setBundle({ bundleId: '1.0.0' });
console.log('Update ready');
```

### Capacitor doctor

Latest Dependencies:

  @capacitor/cli: 6.0.0
  @capacitor/core: 6.0.0
  @capacitor/android: 6.0.0
  @capacitor/ios: 6.0.0

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 6.0.0
  @capacitor/core: 6.0.0
  @capacitor/android: 6.0.0

### Before submitting

- [X] I have read and followed the [bug report guidelines](https://capawesome.io/contributing/bug-reports/).
- [X] I have attached links to possibly related issues and discussions.
- [X] I understand that incomplete issues (e.g. without reproduction) are closed.

**Comment by robingenz** [comment]
Thank you for reporting this. Here is a dev version which should fix this issue:

```
npm i @capawesome/capacitor-live-update@6.0.5-dev.c56b7a8.1715927657
```
