### ISSUE TITLE
bug: FilePicker.pickMedia() dosen't allow anymore to take multiple medias on IOS ?

### ISSUE THREAD

**Issue by maximilien0405** [capawesome-team/capacitor-plugins#191]
### Plugin(s)

- [X] File Picker

### Version

6.0.0

### Platform(s)

- [ ] Android
- [X] iOS
- [ ] Web

### Current behavior

Hello there, first of all thanks for making this plugin. I've been using it and it works great, however i just updated to version 6.0.0 and now i can't select multiple medias on IOS ? It worked on version 5.0 without any problem, so i'm not sure why it's not possible anymore ? This is a big problem for me since i want my user to pick multiple images/videos to send..

### Expected behavior

It's supposed to pick multiple medias if i set the "limit" property to more than 1 (before v6 it had "multiple"), but i lets me choose only one :/

### Capacitor doctor

💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 6.0.0
  @capacitor/core: 6.0.0
  @capacitor/android: 6.0.0
  @capacitor/ios: 6.0.0

Installed Dependencies:

  @capacitor/core: 6.0.0
  @capacitor/android: 6.0.0
  @capacitor/ios: 6.0.0
  @capacitor/cli: 6.0.0

[success] iOS looking great! 👌
[success] Android looking great! 👌

**Comment by robingenz** [comment]
Did you try to set it to 0?

**Comment by maximilien0405** [comment]
@robingenz Oh okay wait maybe i'm just confused.. i tried 0 on the web and i can select multiple of them. I want my user to select max 10 images, however right now the limit is set to 10 and it's only allowing me to select one on IOS 🤔

**Comment by robingenz** [comment]
Which iOS version are you using?

**Comment by maximilien0405** [comment]
@robingenz I just updated to IOS 15.5

**Comment by robingenz** [comment]
Okay, that should work. In this case, please provide a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) using [this template](https://github.com/capawesome-team/.capacitor-app) in a public GitHub repository so I can debug the issue.
