### ISSUE TITLE
feat: adjust alertMessage on iOS

### ISSUE THREAD

**Issue by entwicklung-sanacorp** [capawesome-team/capacitor-plugins#194]
### Plugin(s)

- [ ] Android Foreground Service
- [ ] Android Battery Optimization
- [ ] App Update
- [ ] Background Task
- [ ] Badge
- [ ] Bluetooth Low Energy
- [ ] Cloudinary
- [ ] Datetime Picker
- [ ] File Compressor
- [ ] File Opener
- [ ] File Picker
- [ ] Live Update
- [ ] Managed Configurations
- [X] NFC
- [ ] Photo Editor
- [ ] Printer
- [ ] Screen Orientation
- [ ] Zip

### Current problem

The alertMessage is once set with the startScanSession method. There is no option to change this message, e.g. to show some progress.

### Preferred solution

A method that allows to change the alertMessage string

### Alternative options

Giving a new alertMessage string as a function parameter when calling e.g. the transceive method

### Additional context

https://developer.apple.com/documentation/corenfc/nfcreadersession/2919987-alertmessage

### Before submitting

- [X] I have read and followed the [feature request guidelines](https://capawesome.io/contributing/feature-requests/).
- [X] I have attached links to possibly related issues and discussions.

**Comment by robingenz** [comment]
This feature is now available in version 6.2.0:

```ts
import { Nfc } from "@capawesome-team/capacitor-nfc";

const setAlertMessage = async () => {
	await Nfc.setAlertMessage({ message: "..." });
}
```
