### ISSUE TITLE
feat: min prop does not need to format

### ISSUE THREAD

**Issue by kailichiang** [capawesome-team/capacitor-plugins#207]
### Plugin(s)

- [ ] Android Foreground Service
- [ ] Android Battery Optimization
- [ ] App Update
- [ ] Background Task
- [ ] Badge
- [ ] Bluetooth Low Energy
- [ ] Cloudinary
- [X] Datetime Picker
- [ ] File Compressor
- [ ] File Opener
- [ ] File Picker
- [ ] Live Update
- [ ] Managed Configurations
- [ ] NFC
- [ ] Photo Editor
- [ ] Printer
- [ ] Screen Orientation
- [ ] Zip

### Current problem

When I set format without year, like 'EEE, MMM dd', it doesn't contain year information. Thus, min option would not know the year and set default as 2000. But actually, I'd like to gray out passed day from today.

### Preferred solution

Make min prop not need to match format.

### Before submitting

- [X] I have read and followed the [feature request guidelines](https://capawesome.io/contributing/feature-requests/).
- [X] I have attached links to possibly related issues and discussions.

**Comment by robingenz** [comment]
I don't understand exactly what you mean. Please give me a more detailed example.

**Comment by kailichiang** [comment]
Sorry for not clear. For example, if I set format as **'Mon, Jan 05'**, there is no year. And I set **min** property as **'Thu, Jun 27'** which is **Today**. In this case, when I tap datetime-picker, it will set my year as 2000. So, if I want to use **min** property, my format must contain year. I think the **min** property should be a datetime object but don't need to match format property.

**Comment by kaili58** [comment]
That's a great idea. But my purpose is to disable the date before today in calendar and show in "Mon, Jun 24" format, I need the min property. However, this a good inspiration for me. I can separate date object and the real display format. Though I think the min property should not need to fit the format property, this request can be closed. Many thanks!

**Comment by kailichiang** [comment]
That's a great idea. But my purpose is to disable the date before today in calendar and show format as "Mon, Jun 24", I need the min property. However, this a good inspiration for me. I can separate date object and the real display format. Though I think the min property should not need to fit the format property, this request can be closed. Many thanks!
