### ISSUE TITLE
feat: Support both LandscapeLeft & LandscapeRight for OrientationType.LANDSCAPE

### ISSUE THREAD

**Issue by prathamgahlout** [capawesome-team/capacitor-plugins#208]
### Plugin(s)

- [ ] Android Foreground Service
- [ ] Android Battery Optimization
- [ ] App Update
- [ ] Background Task
- [ ] Badge
- [ ] Bluetooth Low Energy
- [ ] Cloudinary
- [ ] Datetime Picker
- [ ] File Compressor
- [ ] File Opener
- [ ] File Picker
- [ ] Live Update
- [ ] Managed Configurations
- [ ] NFC
- [ ] Photo Editor
- [ ] Printer
- [X] Screen Orientation
- [ ] Zip

### Current problem

I see that for the OrientationType.Landscape we set the orientation as LandscapeRight.
Why can't we support both landscapeLeft and landscapeRight orientations?

### Preferred solution

~~Like for OrientationType.Portrait we support both PortraitUp and PortraitDown~~, OrientationType.Landscape should support both LandscapeLeft & LandscapeRight.

### Before submitting

- [X] I have read and followed the [feature request guidelines](https://capawesome.io/contributing/feature-requests/).
- [X] I have attached links to possibly related issues and discussions.

**Comment by robingenz** [comment]
[Here](https://capawesome.io/plugins/screen-orientation/#orientationtype) you can find a list of all available orientation types. There are no orientation types `PortraitUp` and `PortraitDown`, only `PORTRAIT`, `PORTRAIT_PRIMARY` and `PORTRAIT_SECONDARY`. There are also `LANDSCAPE`, `LANDSCAPE_PRIMARY` and `LANDSCAPE_SECONDARY`.

So what exactly do you mean?

**Comment by prathamgahlout** [comment]
Thank you for replying @robingenz!
Sorry for I was not so clear. Was in a quick hurry when I posted this, I apologize.
I was talking about Orientations for the iOS platform, I should have mentioned it clearly.
So for Portrait, I wanted to say that we can have either Portrait or PortraitUpsideDown.
Similarly, for Landscape we do have LandscapeLeft & LandscapeRight.

[Here](https://github.com/capawesome-team/capacitor-plugins/blob/a0627eb8e7191ab626c79c9993dc7638afca0a30/packages/screen-orientation/ios/Plugin/ScreenOrientation.swift#L120-L137) I see that `OrientationType.Landscape` is being mapped to `UIInterfaceOrientationMask.LandscapeRight`.
I believe we can have an Orientation mask that supports both LandscapeLeft & LandscapeRight ([Link to Apple Docs](https://developer.apple.com/documentation/uikit/uiinterfaceorientationmask/1623106-landscape)) at the same time instead of choosing to lock into any one of those.
Is it possible to lock orientation in `LANDSCAPE` and support both `LANDSCAPE_PRIMARY` & `LANDSCAPE_SECONDARY` currently?

**Comment by robingenz** [comment]
Okay, now i got what you mean.

> Is it possible to lock orientation in `LANDSCAPE` and support both `LANDSCAPE_PRIMARY` & `LANDSCAPE_SECONDARY` currently?

I'm not sure, I would have to take a closer look. But in principle, these changes would be fine with me. Would you be interested in creating a PR?

**Comment by prathamgahlout** [comment]
Yes, I can take this up!

**Comment by prathamgahlout** [comment]
Hi @robingenz, this issue can be closed.

**Comment by robingenz** [comment]
@prathamgahlout Thanks!

Closed by #209
