### ISSUE TITLE
bug: Cannot find 'KeyValueStore' in scope

### ISSUE THREAD

**Issue by n7best** [capawesome-team/capacitor-plugins#211]
### Plugin(s)

- [ ] Android Foreground Service
- [ ] Android Battery Optimization
- [ ] App Update
- [ ] Background Task
- [ ] Badge
- [ ] Bluetooth Low Energy
- [ ] Cloudinary
- [ ] Datetime Picker
- [ ] File Compressor
- [ ] File Opener
- [ ] File Picker
- [X] Live Update
- [ ] Managed Configurations
- [ ] NFC
- [ ] Photo Editor
- [ ] Printer
- [ ] Screen Orientation
- [ ] Zip

### Version

6.0.7

### Platform(s)

- [ ] Android
- [X] iOS
- [ ] Web

### Current behavior

Error during build: `Cannot find 'KeyValueStore' in scope` during build for 
https://github.com/capawesome-team/capacitor-plugins/blob/main/packages/live-update/ios/Plugin/LiveUpdate.swift#L405

### Expected behavior

No Error

### Reproduction

none

### Steps to reproduce

I think this https://github.com/capawesome-team/capacitor-plugins/commit/6d441858266e1dfc5e3e2606a0e71b30540a9742 cause the issue, [6.0.6](https://www.npmjs.com/package/@capawesome/capacitor-live-update/v/6.0.6) works fine

### Capacitor doctor

none

### Before submitting

- [X] I have read and followed the [bug report guidelines](https://capawesome.io/contributing/bug-reports/).
- [X] I have attached links to possibly related issues and discussions.
- [X] I understand that incomplete issues (e.g. without reproduction) are closed.

**Comment by robingenz** [comment]
You need to upgrade to the latest Capacitor version.

**Comment by n7best** [comment]
upgrade capacitor versions from `5` to `6` solve the issue.
