### ISSUE TITLE
bug: reset() followed by reload() don't reset version until app close + open again.

### ISSUE THREAD

**Issue by personalrad** [capawesome-team/capacitor-plugins#212]
### Plugin(s)

- [ ] Android Foreground Service
- [ ] Android Battery Optimization
- [ ] App Update
- [ ] Background Task
- [ ] Badge
- [ ] Bluetooth Low Energy
- [ ] Cloudinary
- [ ] Datetime Picker
- [ ] File Compressor
- [ ] File Opener
- [ ] File Picker
- [x] Live Update
- [ ] Managed Configurations
- [ ] NFC
- [ ] Photo Editor
- [ ] Printer
- [ ] Screen Orientation
- [ ] Zip

### Version

6.0.7

### Platform(s)

- [ ] Android
- [X] iOS
- [ ] Web

### Current behavior

When not connected to Capawesome cloud, doing a reset() follower by a reload() doesn't take effect imediately, only after close and reopen the app.

### Expected behavior

reset() followed by reload() must activate original version instead of needing to close than open the app again.

### Reproduction

https://github.com/capawesome-team/capacitor-plugins

### Steps to reproduce

When not connected to Capawesome cloud, doing a reset() follower by a reload() doesn't take effect imediately, only after close and reopen the app.

If downloadBundle(), then setBundle() then reload(), it takes effect imediately, without needing to close+open the app. 

Temporary solution was, when need to reset the app to default bundle, send it as a new bundle (ex: native version is 1.2, live updated bundle is 1.3. If reset(), it only return to 1.2 after ap close+reopen, but if send a new live update as 1.2 (downloadBundle + setBundle), followed by a reload(), it becomes 1.2 instantly, withou needing to reboot the app.

### Capacitor doctor

💊   Capacitor Doctor  💊

Latest Dependencies:

  @capacitor/cli: 6.1.0
  @capacitor/core: 6.1.0
  @capacitor/android: 6.1.0
  @capacitor/ios: 6.1.0

Installed Dependencies:

  @capacitor/cli: 6.1.0
  @capacitor/core: 6.1.0
  @capacitor/android: 6.1.0
  @capacitor/ios: 6.1.0

[success] iOS looking great! 👌
[success] Android looking great! 👌

### Before submitting

- [X] I have read and followed the [bug report guidelines](https://capawesome.io/contributing/bug-reports/).
- [X] I have attached links to possibly related issues and discussions.
- [X] I understand that incomplete issues (e.g. without reproduction) are closed.

**Comment by robingenz** [comment]
Thank you for reporting this. I will publish a fix later today. 🙌

As I am always looking for feedback: May I ask why you opted for self-hosting?

**Comment by personalrad** [comment]
Thanks for your agility! We chose self-hosted for two reasons: 1) security - the company's policy of minimizing external access and 2) we already have a "controls and adjustments" function in the app via API, we chose to integrate version control into it, because that way we can control via server-side which device to actually send the new bundle.

Is there any way we can contribute financially to the development of the plugin? We would do it with greater joy

**Comment by robingenz** [comment]
@personalrad Thanks for sharing! This is a great way to use the self-hosted option. 

> Is there any way we can contribute financially to the development of the plugin? We would do it with greater joy

Yes, I would love to welcome you as a sponsor. 💜 Here you can find more information: https://capawesome.io/sponsors/#how-to-sponsor. Let me know if you have any questions. You can also reach me via email at [robin@capawesome.io](mailto:robin@capawesome.io).
