### ISSUE TITLE
bug: min and max ignored when setting time in datetime mode

### ISSUE THREAD

**Issue by beard7** [capawesome-team/capacitor-plugins#220]
### Plugin(s)

- [ ] Android Foreground Service
- [ ] Android Battery Optimization
- [ ] App Update
- [ ] Background Task
- [ ] Badge
- [ ] Bluetooth Low Energy
- [ ] Cloudinary
- [X] Datetime Picker
- [ ] File Compressor
- [ ] File Opener
- [ ] File Picker
- [ ] Live Update
- [ ] Managed Configurations
- [ ] NFC
- [ ] Photo Editor
- [ ] Printer
- [ ] Screen Orientation
- [ ] Zip

### Version

5.1.1

### Platform(s)

- [X] Android
- [ ] iOS
- [ ] Web

### Current behavior

Using the DatetimePicker with the following options on Android allows choosing a time outside the specified min/max range:
````
options = {
  cancelButtonText: 'Cancel',
  doneButtonText: 'Ok',
  mode: "datetime",
  format: "yyyy-MM-dd'T'HH:mm",
  value: "2024-07-03T06:28",
  min: "2024-07-03T03:00",
  max: "2024-07-03T09:00",
  theme: 'dark',
  locale: 'en-GB',
  androidTimePickerMode: 'clock',
  androidDatePickerMode: 'calendar',
};
````

All other aspects of the plugin are working as expected. Setting mix/max works well in date mode.

### Expected behavior

After selecting the date, the time should be limited to the range specified by the min/max options.

### Reproduction

.

### Steps to reproduce

```
import { DatetimePicker } from '@capawesome-team/capacitor-datetime-picker';
options = {
  cancelButtonText: 'Cancel',
  doneButtonText: 'Ok',
  mode: "datetime",
  format: "yyyy-MM-dd'T'HH:mm",
  value: "2024-07-03T06:28",
  min: "2024-07-03T03:00",
  max: "2024-07-03T09:00",
  theme: 'dark',
  locale: 'en-GB',
  androidTimePickerMode: 'clock',
  androidDatePickerMode: 'calendar',
};
const result = await DatetimePicker.present(options);
```

### Other information

If it's of any use, the same issue seems to apply when using the alternative `@capacitor-community/date-picker` plugin.

### Capacitor doctor

Latest Dependencies:

  @capacitor/cli: 6.1.0
  @capacitor/core: 6.1.0
  @capacitor/android: 6.1.0
  @capacitor/ios: 6.1.0

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 5.2.2
  @capacitor/android: 5.2.2
  @capacitor/core: 5.2.2

[error] Missing <manifest package=""> attribute in app/src/main

### Before submitting

- [X] I have read and followed the [bug report guidelines](https://capawesome.io/contributing/bug-reports/).
- [X] I have attached links to possibly related issues and discussions.
- [X] I understand that incomplete issues (e.g. without reproduction) are closed.

**Comment by robingenz** [comment]
I could reproduce this issue. However, the problem does not seem to be the plugin but Android. The plugin passes the value correctly to [`setMinDate`](https://github.com/capawesome-team/capacitor-plugins/blob/7aa2c1681dbf46a4057c9aa056dd095eb80c4e1d/packages/datetime-picker/android/src/main/java/io/capawesome/capacitorjs/plugins/datetimepicker/DatetimePicker.java#L119)/[`setMaxDate`](https://github.com/capawesome-team/capacitor-plugins/blob/7aa2c1681dbf46a4057c9aa056dd095eb80c4e1d/packages/datetime-picker/android/src/main/java/io/capawesome/capacitorjs/plugins/datetimepicker/DatetimePicker.java#L122). Unfortunately there is nothing I can do. Therefore I close this issue.

**Comment by beard7** [comment]
Thanks for looking. I thought that may be the case, given that it affects the other Capacitor datetime picker in the same way.
