### ISSUE TITLE
capacitor-file-picker is not obeying permissions settings of photo library

### ISSUE THREAD

**Issue by venna-kalyani** [capawesome-team/capacitor-plugins#236]
### Plugin(s)

- [ ] Android Foreground Service
- [ ] Android Battery Optimization
- [ ] App Update
- [ ] Background Task
- [ ] Badge
- [ ] Bluetooth Low Energy
- [ ] Cloudinary
- [ ] Datetime Picker
- [ ] File Compressor
- [ ] File Opener
- [X] File Picker
- [ ] Live Update
- [ ] Managed Configurations
- [ ] NFC
- [ ] Photo Editor
- [ ] Printer
- [ ] Screen Orientation
- [ ] Zip

### Current problem

We came across a scenario and verified, Filepicker.pickMedia() method is not returning photos based on photos permission that the user has selected (ex: limited access - expecting to return only limited selected photos)

So we are looking for alternative and using Camera.pickLimitedLibraryPhotos() method, when user having limited access permission, while using we get the below output

[{"path":"file:///private/var/mobile/Containers/Data/Application/5A9905CD-7B18-4113-88C7-FC22E13A8ED6/tmp/photo-1.jpg","webPath":"capacitor://localhost:8080/capacitor_file/private/var/mobile/Containers/Data/Application/5A9905CD-7B18-4113-88C7-FC22E13A8ED6/tmp/photo-1.jpg","format":”jpeg”}]

We need the actual file name here for further handling. Any way to get that actual file name here.?

Either way let me know how we can achieve this.

"@capacitor/camera": "^4.1.5",
"@capawesome/capacitor-file-picker": "^0.6.3",

### Preferred solution

It would be good if capacitor-file-picker returns photos based on users permission (like : limited , allow full access)

### Alternative options

It would be good if capacitor-file-picker returns photos based on users permission (like : limited , allow full access)

### Before submitting

- [X] I have read and followed the [feature request guidelines](https://capawesome.io/contributing/feature-requests/).
- [X] I have attached links to possibly related issues and discussions.

**Comment by robingenz** [comment]
I close this as not planned. The [Capacitor File Picker](https://capawesome.io/plugins/file-picker/) plugin uses the [PHPickerViewController](https://developer.apple.com/documentation/photokit/phpickerviewcontroller), which does not require any permissions and therefore is not affected by this setting (see [here](https://stackoverflow.com/a/76228978/6731412)).
