### ISSUE TITLE
bug: Error: "LiveUpdate" plugin is not implemented on android

### ISSUE THREAD

**Issue by mustafa0x** [capawesome-team/capacitor-plugins#243]
### Plugin(s)

- [ ] Android Foreground Service
- [ ] Android Battery Optimization
- [ ] App Update
- [ ] Background Task
- [ ] Badge
- [ ] Bluetooth Low Energy
- [ ] Cloudinary
- [ ] Datetime Picker
- [ ] File Compressor
- [ ] File Opener
- [ ] File Picker
- [X] Live Update
- [ ] Managed Configurations
- [ ] NFC
- [ ] Photo Editor
- [ ] Printer
- [ ] Screen Orientation
- [ ] Zip

### Version

^6.2.0

### Platform(s)

- [X] Android
- [ ] iOS
- [ ] Web

### Current behavior

Error: "LiveUpdate" plugin is not implemented on android

### Expected behavior

to work

### Reproduction

n/a

### Steps to reproduce

n/a

### Capacitor doctor

n/a

### Before submitting

- [X] I have read and followed the [bug report guidelines](https://capawesome.io/contributing/bug-reports/).
- [X] I have attached links to possibly related issues and discussions.
- [X] I understand that incomplete issues (e.g. without reproduction) are closed.

**Comment by robingenz** [comment]
Thank you for reaching out. This error comes from Capacitor and not from the plugin. Please take a look at the [Troubleshooting Android Issues](https://capacitorjs.com/docs/android/troubleshooting#plugin-not-implemented) guide.

**Comment by mustafa0x** [comment]
Thanks @robingenz for the awesome plugin. It was an odd, transient error. Seems to be resolved.

**Comment by robingenz** [comment]
Awesome, you're welcome!
