### ISSUE TITLE
bug: getBundle always returns null for bundleId

### ISSUE THREAD

**Issue by jkyoutsey** [capawesome-team/capacitor-plugins#247]
### Plugin(s)

- [ x] Live Update

### Version

6.2.0

### Platform(s)

- [X] Android
- [X] iOS
- [ ] Web

### Current behavior

When calling `LiveUpdate.sync()` I get a 404, and when trying to `LiveUpdate.getBundle()` it always returns `{ bundleId: null }`
My app id is correct, I've set the channel to "dev" and called `LiveUpdate.ready()`.

### Expected behavior

sync should find new bundles on the specified channel.
getBundle should return the current bundle's id.

### Reproduction

https://github.com/capawesome-team/.capacitor-app

### Steps to reproduce

There isn't a way to provide a reproduction without revealing internal details that should not be shared publicly.
If you ABSOLUTELY need a repro I can create one without the relevant information and provide that in a DM.

### Other information

We are using Capawesome Cloud and have a dev channel set up.

We set the channel to dev, then we call ready(). 

We then have a 60 second timer that calls sync() to check for new bundles.
sync() always returns a 404?
```
[ LiveUpdate ] Fetching latest bundle from  https://api.cloud.capawesome.io/v1/apps/{redacted}/bundles/latest?appVersionCode=84&appVersionName=1.0.13&bundleId=public&deviceId={redacted}&osVersion=17.6&platform=1&pluginVersion=6.2.0
[ LiveUpdate ]  responseValidationFailed(reason: Alamofire.AFError.ResponseValidationFailureReason.unacceptableStatusCode(code: 404))
```

We also want to display the bundle Id in the UI so that we know what's running on a user's device when they report problems. This call always returns a bundle Id of null.

Discord: https://discord.com/channels/520266681499779082/1270002962349162558/1270024491321262090

### Capacitor doctor

Latest Dependencies:

  @capacitor/cli: 6.1.1
  @capacitor/core: 6.1.1
  @capacitor/android: 6.1.1
  @capacitor/ios: 6.1.1

Installed Dependencies:

  @capacitor/cli: 6.1.1
  @capacitor/core: 6.1.1
  @capacitor/android: 6.1.1
  @capacitor/ios: 6.1.1

### Before submitting

- [X] I have read and followed the [bug report guidelines](https://capawesome.io/contributing/bug-reports/).
- [X] I have attached links to possibly related issues and discussions.
- [X] I understand that incomplete issues (e.g. without reproduction) are closed.

**Comment by robingenz** [comment]
The problem was that no channel was set. I close this issue as completed.
