### ISSUE TITLE
feat: Searching for NFC Cordova plugin

### ISSUE THREAD

**Issue by Ujjwal-800** [capawesome-team/capacitor-plugins#259]
### Name

NFC Cordova plugin

### Platform(s)

- [X] Android
- [X] iOS
- [ ] Web

### Description

I have requirement to implement NFC in my Cordova project but i am unable to use native-plugin,
Can you please help me to find any plugin which will support in Cordova with ionic7 or ionic5 app

### Before submitting

- [X] I have read and followed the [plugin request guidelines](https://capawesome.io/contributing/plugin-requests/).
- [X] I have attached links to possibly related issues and discussions.

**Comment by robingenz** [comment]
Please reach out via email: [support@capawesome.io](mailto:support@capawesome.io).
