### ISSUE TITLE
bug: App crashes on paper format change when printing

### ISSUE THREAD

**Issue by DontGiveAFck** [capawesome-team/capacitor-plugins#268]
### Plugin(s)

- [ ] Android Foreground Service
- [ ] Android Battery Optimization
- [ ] App Update
- [ ] Background Task
- [ ] Badge
- [ ] Bluetooth Low Energy
- [ ] Cloudinary
- [ ] Datetime Picker
- [ ] File Compressor
- [ ] File Opener
- [ ] File Picker
- [ ] Live Update
- [ ] Managed Configurations
- [ ] NFC
- [ ] Photo Editor
- [X] Printer
- [ ] Screen Orientation
- [ ] Zip

### Version

6.0.1

### Platform(s)

- [X] Android
- [ ] iOS
- [ ] Web

### Current behavior

User can't change orientation / paper format in print modal - it leads to app crash

### Expected behavior

User can change orientation / paper format without app crash

### Reproduction

https://github.com/DontGiveAFck/capacitor-printer-issues

### Steps to reproduce

Steps to install and run app:
1. clone rep from 'Reproduction'
2. add your auth token to install printer plugin
3. npm install -> ionic cap sync android -> open and run app

Steps to reproduce:
1. click on 'Print PDF'
2. Select printer or 'Save as PDF' output type
3. change paper size to 'ISO A4' or Orientation to 'Landscape'
4. App crashed.

### Capacitor doctor

💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 6.1.2
  @capacitor/core: 6.1.2
  @capacitor/android: 6.1.2
  @capacitor/ios: 6.1.2

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 6.1.2
  @capacitor/core: 6.1.2
  @capacitor/android: 6.1.2

[success] Android looking great! 👌

### Before submitting

- [X] I have read and followed the [bug report guidelines](https://capawesome.io/contributing/bug-reports/).
- [X] I have attached links to possibly related issues and discussions.
- [X] I understand that incomplete issues (e.g. without reproduction) are closed.

**Comment by robingenz** [comment]
Thank you for reporting this. I can reprodue the issue. The following error is printed in logcat:

```
java.lang.RuntimeException: Cannot print a malformed PDF file
	at android.print.PrintManager$PrintDocumentAdapterDelegate$MyHandler.handleMessage(PrintManager.java:1127)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8592)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
```

I will take a look at it.

**Comment by robingenz** [comment]
I have just published a fix:

```
npm i @capawesome-team/capacitor-printer@6.0.2
```

<img src="https://github.com/user-attachments/assets/36b43303-52b5-4496-b5fb-e4dc65913860" width="266" />

Thanks again for reporting this.
