### ISSUE TITLE
bug: Badge.set() not working on iOS

### ISSUE THREAD

**Issue by wwwguy** [capawesome-team/capacitor-plugins#269]
### Plugin(s)

- [ ] Android Foreground Service
- [ ] Android Battery Optimization
- [ ] App Update
- [ ] Background Task
- [X] Badge
- [ ] Bluetooth Low Energy
- [ ] Cloudinary
- [ ] Datetime Picker
- [ ] File Compressor
- [ ] File Opener
- [ ] File Picker
- [ ] Live Update
- [ ] Managed Configurations
- [ ] NFC
- [ ] Photo Editor
- [ ] Printer
- [ ] Screen Orientation
- [ ] Zip

### Version

6.0.0

### Platform(s)

- [ ] Android
- [X] iOS
- [ ] Web

### Current behavior

Following the the standard docs, everything works fine on Android but the app icon badge number is not changed on iOS.

### Expected behavior

The app icon badge number should change on iOS when Badge.set() is called (and works fine on Android).

### Reproduction

https://github.com/wwwguy/cap-badge

### Steps to reproduce

1. From xCode run iOS 
2. Confirm whether the app icon badge is added

### Other information

The PrivacyInfo.xcprivacy file was created via xCode per the documentation;

> < ?xml version="1.0" encoding="UTF-8"?>
> < !DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
> < plist version="1.0">
> < dict>
> < key>NSPrivacyAccessedAPITypes</key>
> < array>
> < !-- Add this dict entry to the array if the file already exists. -->
> < dict>
> < key>NSPrivacyAccessedAPIType</key>
> < string>NSPrivacyAccessedAPICategoryUserDefaults</string>
> < key>NSPrivacyAccessedAPITypeReasons</key>
> < array>
> < string>CA92.1</string>
> < /array>
> < /dict>
> < /array>
> < /dict>
> < /plist>

### Capacitor doctor

💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 6.1.2
  @capacitor/core: 6.1.2
  @capacitor/android: 6.1.2
  @capacitor/ios: 6.1.2

Installed Dependencies:

  @capacitor/cli: 6.1.2
  @capacitor/android: 6.1.2
  @capacitor/core: 6.1.2
  @capacitor/ios: 6.1.2

[success] iOS looking great! 👌
[success] Android looking great! 👌

### Before submitting

- [X] I have read and followed the [bug report guidelines](https://capawesome.io/contributing/bug-reports/).
- [X] I have attached links to possibly related issues and discussions.
- [X] I understand that incomplete issues (e.g. without reproduction) are closed.

**Comment by robingenz** [comment]
Did you request permissions?

**Comment by wwwguy** [comment]
Yes, I didn't include it in the repo to simplify things but when we use the following as a precursor to setting the badge value it does not work:

> const result = await Badge.checkPermissions().then(async response => {
>     console.log(JSON.stringify(response));
>     const set = async () => {
>         await Badge.set(5);
>     };
> });

It does log that permission was granted:

> {"display":"granted"}

But the app icon badge does not display.

**Comment by wwwguy** [comment]
Ok no problem - I have updated the repo - https://github.com/wwwguy/cap-badge

**Comment by robingenz** [comment]
You are not using the template I provided a link to. Angular is not needed to reproduce the issue, is it?

**Comment by wwwguy** [comment]
I'm just providing the minimal reproducible example code in use with Ionic Capacitor apps v 6.0. We can remove angular if you want (maybe it will work then?) but just reporting this as it used to work fine in previous versions.

**Comment by robingenz** [comment]
As i said, please provide a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) using [this template](https://github.com/capawesome-team/.capacitor-app) in a public GitHub repository.

**Comment by wwwguy** [comment]
Thanks anyway...  it really does no good to strip it all the way down to such a minimal test environment that it has no reflection on actual use on a live iOS device through Ionic Capacitor w/Angular. We were just trying to help as we've used this plugin for many years and versions of Capacitor without any problems... yet now it no longer works on iOS. All good, we'll find another solution or just build our own. Be well.

**Comment by robingenz** [comment]
The more code and dependencies your reproducible example has, the longer it will take me to understand and reproduce the problem. It should therefore be in your interest to make it as easy as possible for me to help you. It wouldn't be possible to offer more than 25 plugins for free if I didn't get support from the community. I am closing this issue as no minimal, repdoucible example has been provided.
