### ISSUE TITLE
feat: Posthog Capacitor Plugin

### ISSUE THREAD

**Issue by mariusbolik** [capawesome-team/capacitor-plugins#270]
### Plugin(s)

- [ ] Android Foreground Service
- [ ] Android Battery Optimization
- [ ] App Update
- [ ] Background Task
- [ ] Badge
- [ ] Bluetooth Low Energy
- [ ] Cloudinary
- [ ] Datetime Picker
- [ ] File Compressor
- [ ] File Opener
- [ ] File Picker
- [ ] Live Update
- [ ] Managed Configurations
- [ ] NFC
- [ ] Photo Editor
- [ ] Printer
- [ ] Screen Orientation
- [ ] Zip

### Current problem

![posthog_c12796ec9c](https://github.com/user-attachments/assets/80a59b94-07c1-48c8-a7e1-49bc59fbfe77)

I know you are a big fan of Firebase, but Posthog is a very promising **(and privacy focussed 👀)** alternative. It is very popular in the indie hacker scene and seems to be the most developer focussed analytics platform.

PostHog helps developers understand how users use their product, figure out ways to improve it, and ship new features faster. It does this through features like:

- Anonymous and identified event capture, supports both autocapture and custom events
- Frontend and backend SDKs
- A full product analytics platform with trends, funnels, retention, SQL, and more
- A simplified web analytics dashboard with session duration, bounce rates, and channel analysis
- Session replays with event timeline, console and performance capture, and mobile recording
- Heatmaps, clickmaps, scrollmaps
- Open Source

Website: https://posthog.com/

### Preferred solution

It would be very cool if you could turn their [android](https://posthog.com/docs/libraries/android) and [ios](https://posthog.com/docs/libraries/ios) sdk into an an capacitor plugin :)

### Alternative options

It should be possible to use their js sdk in an capacitor app but I don't think it'll be possible to get as in-depth analytics as with the ios/android sdk.

### Before submitting

- [X] I have read and followed the [feature request guidelines](https://capawesome.io/contributing/feature-requests/).
- [X] I have attached links to possibly related issues and discussions.

**Comment by robingenz** [comment]
> It should be possible to use their js sdk in an capacitor app but I don't think it'll be possible to get as in-depth analytics as with the ios/android sdk.

Would be interesting to know if the Android and iOS SDK actually provides more information. If so, this would definitely be a good plugin.

Maybe Posthog is interested in sponsoring this issue. Are you in contact with them?

**Comment by mariusbolik** [comment]
Here is the official statement from the Posthog Team regarding this topic:

<img src="https://github.com/user-attachments/assets/bf94bdeb-d8c3-4adb-b001-5b7c789b7426" alt="Posthog Forum Screenshot" height="220px" />

Link: https://posthog.com/questions/see-i-os-version-of-users

**Comment by robingenz** [comment]
@mariusbolik I've just published a first dev version:

```
npm i https://pkg.pr.new/capawesome-team/capacitor-plugins/@capawesome/capacitor-posthog@ce53ec9
```

I would really appreciate your feedback.
