### ISSUE TITLE
bug (app update):  The file “lookup” couldn’t be opened.

### ISSUE THREAD

**Issue by jetie000** [capawesome-team/capacitor-plugins#273]
### Plugin(s)

- [ ] Android Foreground Service
- [ ] Android Battery Optimization
- [X] App Update
- [ ] Background Task
- [ ] Badge
- [ ] Bluetooth Low Energy
- [ ] Cloudinary
- [ ] Datetime Picker
- [ ] File Compressor
- [ ] File Opener
- [ ] File Picker
- [ ] Live Update
- [ ] Managed Configurations
- [ ] NFC
- [ ] Photo Editor
- [ ] Printer
- [ ] Screen Orientation
- [ ] Zip

### Version

6.0.0

### Platform(s)

- [ ] Android
- [X] iOS
- [ ] Web

### Current behavior

![Снимок экрана 2024-08-27 в 18 26 03](https://github.com/user-attachments/assets/74b00044-6474-4a8e-ba3b-1b9e10b54513)

This error raises once in 2-3 time when I call 
**AppUpdate.getAppUpdateInfo()**
in the onMounted at App.vue

Line:
https://github.com/capawesome-team/capacitor-plugins/blob/main/packages/app-update/ios/Plugin/AppUpdatePlugin.swift#L30

### Expected behavior

The error isn't raised and function returning update info

### Reproduction

-

### Steps to reproduce

I am using Ionic 8 with Vue 3, Capacitor 6
All the application works fine without using that method
My functions

```
export async function getCurrentAppVersion(platform: string) {
  const result = await AppUpdate.getAppUpdateInfo();
  if (platform === 'android') {
    return result.currentVersionCode;
  }
  return result.currentVersionName;
}

export async function isUpdateAvailable() {
  const result = await AppUpdate.getAppUpdateInfo();
  return result.updateAvailability === AppUpdateAvailability.UPDATE_AVAILABLE;
}
```

### Capacitor doctor

💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 6.1.2
  @capacitor/core: 6.1.2
  @capacitor/android: 6.1.2
  @capacitor/ios: 6.1.2

Installed Dependencies:

  @capacitor/cli: 6.1.0
  @capacitor/core: 6.1.1
  @capacitor/android: 6.1.1
  @capacitor/ios: 6.1.1

[success] iOS looking great! 👌
[success] Android looking great! 👌

### Before submitting

- [X] I have read and followed the [bug report guidelines](https://capawesome.io/contributing/bug-reports/).
- [X] I have attached links to possibly related issues and discussions.
- [X] I understand that incomplete issues (e.g. without reproduction) are closed.

**Comment by robingenz** [comment]
Unfortunately I cannot reproduce this issue. Feel free to create a PR.

**Comment by tanuj-g** [comment]
@robingenz 
I am also facing the same issue, 

@jetie000 did you found any solution of it yet?

**Comment by anuragmadhur** [comment]
> @robingenz I am also facing the same issue,
> 
> @jetie000 did you found any solution of it yet?

+1

**Comment by jetie000** [comment]
Can't reproduce today with the same configuration :/

**Comment by tanuj-g** [comment]
> Can't reproduce today with the same configuration :/ Maybe is was a problem with Apple API and they repaired it

Are you sure, this was the issue from Apple API & now it is resolved, I am regularly getting sentry issues due to this
If you notice it happened in last 14 minutes too

![Screenshot 2024-08-29 at 12 21 20 PM](https://github.com/user-attachments/assets/e141ae84-85ee-4aed-91db-89041d2b4096)
