### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by tarangshah19** [capawesome-team/capacitor-plugins#29]
### Plugin(s)

- [X] App Update
- [ ] Background Task
- [ ] Badge
- [ ] Cloudinary
- [ ] File Picker
- [ ] Managed Configurations
- [ ] Photo Editor
- [ ] Screen Orientation

### Did you test the latest version?

- [X] I use the latest version

### Platform(s)

- [X] Android
- [ ] iOS
- [ ] Web

### Current behavior

update app popup alwase show & not get updated from android Store there able to see update button 

`const result = await AppUpdate.getAppUpdateInfo();
    console.log('result', result);
    console.log('AppUpdateAvailability',AppUpdateAvailability)

  if (result.updateAvailability !== AppUpdateAvailability.UPDATE_AVAILABLE) {
    console.log('first')
    return;
  }
  if (result.immediateUpdateAllowed) {
    console.log('secound')
    await AppUpdate.performImmediateUpdate();
  } 
  }`

### Expected behavior

Must update from store once when update is there

### Reproduction

https://github.com/kutumbh/mobile-ux-app/

### Steps to reproduce

1. add this code on app.vue
2. generate apk from android studio for old ver.
3. intall on mobile 
4. when you open app its keep alwase showing 

### Capacitor doctor

Latest Dependencies:

  @capacitor/cli: 4.7.3
  @capacitor/core: 4.7.3
  @capacitor/android: 4.7.3
  @capacitor/ios: 4.7.3

Installed Dependencies:

  @capacitor/cli: 4.7.3
  @capacitor/android: 4.7.3
  @capacitor/core: 4.7.3
  @capacitor/ios: 4.7.3

[success] iOS looking great! 👌
[success] Android looking great! 👌

### Before submitting

- [X] I understand that incomplete issues (e.g. without reproduction) are closed.

**Comment by robingenz** [comment]
Your reproduction repository seems to be private.

**Comment by tarangshah19** [comment]
yes its a private i will share code hear
App.vue checkAppUpdate called in mounted

import { AppUpdate, AppUpdateAvailability } from '@capawesome/capacitor-app-update';
`
async checkAppUpdate () {
      const result = await AppUpdate.getAppUpdateInfo();
      console.log(result)
  if (result.updateAvailability !== AppUpdateAvailability.UPDATE_AVAILABLE) {
    return;
  }
  if (result.immediateUpdateAllowed) {
    console.log(AppUpdate)
    await AppUpdate.performImmediateUpdate();
  }
    },
`

**Comment by robingenz** [comment]
Please post a screen recording that shows the problem.

**Comment by tarangshah19** [comment]
https://user-images.githubusercontent.com/73467634/233045584-8e053ed7-e3c6-435d-bf43-f4ad5d5e0d97.mp4

**Comment by robingenz** [comment]
I can see on the video that you installed the app locally using the file manager. However, you need to test the app via internal app sharing, see [Test with internal app sharing](https://github.com/capawesome-team/capacitor-plugins/tree/main/packages/app-update#test-with-internal-app-sharing).

**Comment by tarangshah19** [comment]
ok i will check thanks

**Comment by tarangshah19** [comment]
i have tested with test with internal app sharing now update screen not get internal app sharing ver. 1.10 and in market i have 1.11

**Comment by robingenz** [comment]
Please take a look at the [`Troubleshoot`](https://developer.android.com/guide/playcore/in-app-updates/test#troubleshoot) section and make sure that you have tried everything.
There is unfortunately not much I can do to debug that, as it depends heavily on the setup. I can only give you tips to find a solution.
