### ISSUE TITLE
feat: 

### ISSUE THREAD

**Issue by ewwwgiddings** [capawesome-team/capacitor-plugins#294]
### Plugin(s)

- [ ] Android Foreground Service
- [ ] Android Battery Optimization
- [ ] App Update
- [ ] Background Task
- [ ] Badge
- [ ] Bluetooth Low Energy
- [ ] Cloudinary
- [ ] Datetime Picker
- [ ] File Compressor
- [ ] File Opener
- [ ] File Picker
- [ ] Live Update
- [ ] Managed Configurations
- [ ] NFC
- [ ] Photo Editor
- [ ] Printer
- [ ] Screen Orientation
- [X] Zip

### Current problem

The `Zip` plugin says it's Sponsorware and that it will be released once the goal is met. However, there is no insight on what the goal is or anything about this goal.

### Preferred solution

Can we know the goal and when `Zip` will become publicly available?

### Alternative options

Paying for a subscription but there's no insight on when it will be released otherwise. Using other versions or the old ionic-native version but that is not ideal. Not using `Zip`

### Additional context

I was using ionic-native `Zip`. I see this is now not available through them. I came here to see `Zip` a project. The project is Sponsorware and will be publicly available when the goal is met. The goal is not known or published as far as I can tell. There are green check marks next to it on the wiki though.

https://capawesome.io/plugins/zip/#capawesome-teamcapacitor-zip

### Before submitting

- [X] I have read and followed the [feature request guidelines](https://capawesome.io/contributing/feature-requests/).
- [X] I have attached links to possibly related issues and discussions.

**Comment by robingenz** [comment]
Thank you for your request. I've just added the missing goals: https://capawesome.io/sponsors/insiders/#goals I close this issue since it's not a plugin feature request.
