### ISSUE TITLE
feat: Options for resizing and changing image quality when using FilePicker

### ISSUE THREAD

**Issue by webfletch** [capawesome-team/capacitor-plugins#298]
### Plugin(s)

- [ ] Android Foreground Service
- [ ] Android Battery Optimization
- [ ] App Update
- [ ] Background Task
- [ ] Badge
- [ ] Bluetooth Low Energy
- [ ] Cloudinary
- [ ] Datetime Picker
- [ ] File Compressor
- [ ] File Opener
- [X] File Picker
- [ ] Live Update
- [ ] Managed Configurations
- [ ] NFC
- [ ] Photo Editor
- [ ] Printer
- [ ] Screen Orientation
- [ ] Zip

### Current problem

Need the ability to resize and reduce the quality of images selected from the image library. 

Images taken on phone camera's are usually very high resolution and therefore very large to store or upload.

### Preferred solution

The official Capacitor Camera plugin allows you to pass through parameters to resize and reduce the quality of the images returned, so something similar to that would be great:

```
const options: PickImageOptions = {
   quality: 0.8,
   maxWidth: 400,
   maxHeight: 200
 };

const images = await FilePicker.pickImages(options);
```

### Before submitting

- [X] I have read and followed the [feature request guidelines](https://capawesome.io/contributing/feature-requests/).
- [X] I have attached links to possibly related issues and discussions.

**Comment by robingenz** [comment]
That's what the [File Compressor](https://capawesome.io/plugins/file-compressor/) plugin is for. Changing the image quality is already possible. For resizing, there is already a feature request: https://github.com/capawesome-team/capacitor-plugins/issues/128
