### ISSUE TITLE
bug: Remove unused dependency inflight@1.0.6

### ISSUE THREAD

**Issue by winstonDeGreef** [capawesome-team/capacitor-plugins#300]
### Plugin(s)

- [ ] Android Foreground Service
- [ ] Android Battery Optimization
- [ ] App Update
- [ ] Background Task
- [ ] Badge
- [ ] Bluetooth Low Energy
- [ ] Cloudinary
- [ ] Datetime Picker
- [ ] File Compressor
- [ ] File Opener
- [ ] File Picker
- [ ] Live Update
- [X] Managed Configurations
- [ ] NFC
- [ ] Photo Editor
- [ ] Printer
- [ ] Screen Orientation
- [ ] Zip

### Version

6.0.0

### Platform(s)

- [X] Android
- [X] iOS
- [X] Web

### Current behavior

When installing this plugin you get the following scary warning:

```
npm WARN deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
```

As far as I can tell this module isn't actually used, so it should be removed

### Expected behavior

n/a

### Reproduction

n/a

### Steps to reproduce

install the module

### Capacitor doctor

n/a

### Before submitting

- [X] I have read and followed the [bug report guidelines](https://capawesome.io/contributing/bug-reports/).
- [X] I have attached links to possibly related issues and discussions.
- [X] I understand that incomplete issues (e.g. without reproduction) are closed.

**Comment by robingenz** [comment]
Please take a look at the plugins dependencies: https://github.com/capawesome-team/capacitor-plugins/blob/main/packages/managed-configurations/package.json

We do not actively use the `inflight` package. It must therefore be a dependency of another dependency. I am therefore closing this issue.
