### ISSUE TITLE
feat: iOS NFC reading support for ISO 14443-3A NfcA tags

### ISSUE THREAD

**Issue by gordins** [capawesome-team/capacitor-plugins#316]
### Plugin(s)

- [ ] Android Foreground Service
- [ ] Android Battery Optimization
- [ ] App Update
- [ ] Background Task
- [ ] Badge
- [ ] Bluetooth Low Energy
- [ ] Cloudinary
- [ ] Datetime Picker
- [ ] File Compressor
- [ ] File Opener
- [ ] File Picker
- [ ] Live Update
- [ ] Managed Configurations
- [X] NFC
- [ ] Photo Editor
- [ ] Printer
- [ ] Screen Orientation
- [ ] Zip

### Current problem

The NFC reader on iOS does not scan ISO 14443-3A NfcA type tags. Those are accessible via iOS API but not exposed via the `Nfc.startScanSession` method.

### Preferred solution

We should have an option for the `startScanSession` method to enrich the reading compatibility of NFC tags on iOS so that ISO 14443-3A NfcA can be supported.

### Alternative options

An alternative option could be having this kind of tags scannable by default in the startScanSession, but given that this might need a older/different API, having it expose via an option might be the better alternative.

### Additional context

[Initial discord question](https://discord.com/channels/997595742128578722/997596810715598898/1298718511807336464) 

### Before submitting

- [X] I have read and followed the [feature request guidelines](https://capawesome.io/contributing/feature-requests/).
- [X] I have attached links to possibly related issues and discussions.

**Comment by robingenz** [comment]
Hey @gordins, thank you for creating this issue! I worked on a solution last week and just created a dev release:

```
npm i @capawesome-team/capacitor-nfc@6.3.0-dev.611787f.1730700274
```

This release adds a new `compatbilityMode` option to the `startScanSession` method:

```ts
const read = async () => {
  return new Promise((resolve) => {
    Nfc.addListener('nfcTagScanned', async (event) => {
      await Nfc.stopScanSession();
      resolve(event.nfcTag);
    });

    Nfc.startScanSession({
		compatbilityMode: true
	});
  });
};
```

Please give it a try and let me know if this resolves your issue.

**Comment by gordins** [comment]
Hi @robingenz,

Tested your build. It works great, thank you! Can you add it in an official release?

**Comment by robingenz** [comment]
@gordins I'm really glad it works. Yes, i will publish it later today.
