### ISSUE TITLE
bug: Airplane mode throws weird error

### ISSUE THREAD

**Issue by HarelM** [capawesome-team/capacitor-plugins#317]
### Plugin(s)

- [ ] Android Foreground Service
- [ ] Android Battery Optimization
- [X] App Update
- [ ] Background Task
- [ ] Badge
- [ ] Bluetooth Low Energy
- [ ] Cloudinary
- [ ] Datetime Picker
- [ ] File Compressor
- [ ] File Opener
- [ ] File Picker
- [ ] Live Update
- [ ] Managed Configurations
- [ ] NFC
- [ ] Photo Editor
- [ ] Printer
- [ ] Screen Orientation
- [ ] Zip

### Version

6.0.0

### Platform(s)

- [ ] Android
- [X] iOS
- [ ] Web

### Current behavior

The following method throws an error when starting the app in airplane mode on iOS:
```
import { AppUpdate, AppUpdateAvailability } from '@capawesome/capacitor-app-update';

const result = await AppUpdate.getAppUpdateInfo();
```

### Expected behavior

No error and the return value should be UNKNOWN.

### Reproduction

let me know if this is really needed and I'll work to create it...

### Steps to reproduce

1. Change iOS device to airplane mode
2. Start the app that calls the `getAppUpdateInfo` method

### Other information

I can wrap my code with try-catch to work around this, but in Android this works as expected, and I was expecting iOS to behave the same.
I have verified this happens on multiple iOS devices running my app.
I'm getting a weird error, the following is the log from xcode:
```
To Native ->  App addListener 124148451
⚡️  To Native ->  AppUpdate getAppUpdateInfo 124148452
2024-10-24 23:42:47.784618+0300 App[806:24750] Connection 1: received failure notification
2024-10-24 23:42:47.784767+0300 App[806:24750] Connection 1: failed to connect 1:50, reason -1
2024-10-24 23:42:47.784829+0300 App[806:24750] Connection 1: encountered error(1:50)
2024-10-24 23:42:47.810260+0300 App[806:24690] Error getting network data status Error Domain=NSPOSIXErrorDomain Code=19 "Operation not supported by device"
2024-10-24 23:42:47.810517+0300 App[806:24690] Task <D2F6C0B9-C2E4-4EC6-8BF2-213E46CA651E>.<0> HTTP load failed, 0/0 bytes (error code: -1009 [1:50])
2024-10-24 23:42:47.811818+0300 App[806:24690] NSURLConnection finished with error - code -1009
ERROR MESSAGE:  {"errorMessage":"לא ניתן לפתוח את הקובץ ״lookup״.","message":"לא ניתן לפתוח את הקובץ ״lookup״."}
⚡️  [error] - {"errorMessage":"לא ניתן לפתוח את הקובץ ״lookup״.","message":"לא ניתן לפתוח את הקובץ ״lookup״."}
⚡️  [error] - {"errorMessage":"לא ניתן לפתוח את הקובץ ״lookup״."}
```
לא ניתן לפתוח את הקובץ ״lookup״
Translates to: Unable to open the file "lookup"

The following is my code if that helps - very basic...
https://github.com/IsraelHikingMap/Site/blob/4a2f2b82f2503e33f95b7977e6f47bdabb87630b/IsraelHiking.Web/src/application/services/application-update.service.ts#L15

Please let me know if there are code changes in iOS I can try out, I have no problem reproducing this issue and test any fix you might want me to try out.

### Capacitor doctor

💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 6.1.2
  @capacitor/core: 6.1.2
  @capacitor/android: 6.1.2
  @capacitor/ios: 6.1.2

Installed Dependencies:

  @capacitor/cli: 6.1.2
  @capacitor/core: 6.1.2
  @capacitor/android: 6.1.2
  @capacitor/ios: 6.1.2

[success] iOS looking great! 👌
[success] Android looking great! 👌

### Before submitting

- [X] I have read and followed the [bug report guidelines](https://capawesome.io/contributing/bug-reports/).
- [X] I have attached links to possibly related issues and discussions.
- [X] I understand that incomplete issues (e.g. without reproduction) are closed.

**Comment by robingenz** [comment]
It is intended that an error is thrown in this case because the HTTP request fails. Under Android, no HTTP request is made, but an Android SDK is used and `UNKNOWN` is a valid value there.

**Comment by HarelM** [comment]
Thanks for the quick response!
I find it to be problematic when using the same API for iOS and Android and getting different results, this misses the point of capacitor a bit from my point of view. 
If there's a difference between how iOS and Android are working I would've expected to see it in the docs somewhere...
Thanks for all the hard work put into these plugins!

**Comment by robingenz** [comment]
The API should behave the same on both platforms. If the Android SDK throws an error, then this is also forwarded to the WebView. From my point of view, an HTTP error on iOS simply does not mean that the update availability is unknown, but that there was an error with the request.

**Comment by HarelM** [comment]
Is it possible to check if there's a network availability before sending the request or check the returned error?
What other scenarios can throw an error?
What's the difference between an unknown state and any other error? Why not classify all errors as unknown?

**Comment by robingenz** [comment]
> Is it possible to check if there's a network availability before sending the request or check the returned error?

Sure, that's what the [Network](https://capacitorjs.com/docs/apis/network) plugin is for.

> What other scenarios can throw an error?

There are two lines that can throw errors:

1. https://github.com/capawesome-team/capacitor-plugins/blob/b278a5288e8a7c936d5c3b7d5fdaaf6dbba569cc/packages/app-update/ios/Plugin/AppUpdatePlugin.swift#L30
2. https://github.com/capawesome-team/capacitor-plugins/blob/b278a5288e8a7c936d5c3b7d5fdaaf6dbba569cc/packages/app-update/ios/Plugin/AppUpdatePlugin.swift#L32

>  What's the difference between an unknown state and any other error? Why not classify all errors as unknown?

An error is an unintended event. For example, one of my customers uses the following implementation: If the update availability is unkown, the user is informed that no update is currently available. If an error is thrown, the user is informed that they should try again later.

**Comment by HarelM** [comment]
Isn't the unknown defined that the user should try later?
In any case, I wrapped the call with a try-catch which serves my needs. 
Thanks a lot for taking the time to respond here, truly appreciated! 
I think we have different perspective what each state should be representing and I'm guessing this is what this is all about, and since you maintain this code it is up to you to decide, and I fully respect your decision. 
Thanks again!
