### ISSUE TITLE
feat: add `app-review` plugin

### ISSUE THREAD

**Issue by robingenz** [capawesome-team/capacitor-plugins#320]
### Name

App Review

### Platform(s)

- [X] Android
- [X] iOS
- [ ] Web

### Description

I need a Capacitor plugin that offers me the following two features:

1. Request an app review from within the app.
2. Open the app store so that the user can submit a review there.

The types could look like this:

```ts
export interface AppReviewPlugin {
  /**
   * Open the App Store page for the current app and, if possible, open the dialog to leave a review.
   * 
   * Only available on Android and iOS.
   * 
   * @since 6.0.0
   */
	openAppStore(): Promise<void>;
  /**
   * Request an in-app review.
   * 
   * Only available on Android and iOS.
   * 
   * @since 6.0.0
   */
	requestReview(): Promise<void>;
}
```

If someone wants to work on this issue, please let me know before starting. I will then create the boilerplate code first so that you only have to create the actual implementation.

### Before submitting

- [X] I have read and followed the [plugin request guidelines](https://capawesome.io/contributing/plugin-requests/).
- [X] I have attached links to possibly related issues and discussions.

**Comment by mertyldrr** [comment]
hi, I'd like to work on this if possible :)

**Comment by robingenz** [comment]
Awesome, thank you! 🙏🏻 I will create the boilerplate code for you tomorrow.
