### ISSUE TITLE
feat: Authorisation support for NFC cards

### ISSUE THREAD

**Issue by pefka** [capawesome-team/capacitor-plugins#321]
### Plugin(s)

- [ ] Android Foreground Service
- [ ] Android Battery Optimization
- [ ] App Update
- [ ] Background Task
- [ ] Badge
- [ ] Bluetooth Low Energy
- [ ] Cloudinary
- [ ] Datetime Picker
- [ ] File Compressor
- [ ] File Opener
- [ ] File Picker
- [ ] Live Update
- [ ] Managed Configurations
- [X] NFC
- [ ] Photo Editor
- [ ] Printer
- [ ] Screen Orientation
- [ ] Speech Recognition
- [ ] Zip

### Current problem

I can't find a way to make communication between the card and smartphone encrypted.

### Preferred solution

There is a MiFare desFire card, it supports encrypted communication through authorisation.

Can you add to your plugin the possibility of read with authorisation and write with authorisation? 

### Before submitting

- [X] I have read and followed the [feature request guidelines](https://capawesome.io/contributing/feature-requests/).
- [x] I have attached links to possibly related issues and discussions.

**Comment by robingenz** [comment]
Which platforms must be supported?

**Comment by pefka** [comment]
iOS and Android

**Comment by robingenz** [comment]
I'm not sure if it's possible on iOS. Core NFC only offers two methods for MiFare tags:

1. [sendMiFareCommand](https://developer.apple.com/documentation/corenfc/nfcmifaretag/3585174-sendmifarecommand)
2. [sendMiFareISO7816Command](https://developer.apple.com/documentation/corenfc/nfcmifaretag/3585175-sendmifareiso7816command)

The first is already available via the plugin. You may simply have to send a special command to the tag. However, I have never tested this myself. Feel free to give it a try using the [`transceive(...)`](https://capawesome.io/plugins/nfc/#transceive) method of the plugin. 

Android, on the other hand, offers the following two methods:

1. [authenticateSectorWithKeyA](https://developer.android.com/reference/android/nfc/tech/MifareClassic#authenticateSectorWithKeyA(int,%20byte[]))
2. [authenticateSectorWithKeyB](https://developer.android.com/reference/android/nfc/tech/MifareClassic#authenticateSectorWithKeyB(int,%20byte[]))

I guess these are the methods you are looking for. Both should be easy to implement.

**Comment by robingenz** [comment]
@pefka Have you had a chance to test the `transceive(...)` on iOS? Are you interested in using the other two methods on Android? If so, I would put that on my todo list.
