### ISSUE TITLE
feat: method for updating foreground service notification

### ISSUE THREAD

**Issue by xsorifc28** [capawesome-team/capacitor-plugins#327]
### Plugin(s)

- [X] Android Foreground Service
- [ ] Android Battery Optimization
- [ ] App Update
- [ ] Background Task
- [ ] Badge
- [ ] Bluetooth Low Energy
- [ ] Cloudinary
- [ ] Datetime Picker
- [ ] File Compressor
- [ ] File Opener
- [ ] File Picker
- [ ] Live Update
- [ ] Managed Configurations
- [ ] NFC
- [ ] Photo Editor
- [ ] Printer
- [ ] Screen Orientation
- [ ] Speech Recognition
- [ ] Zip

### Current problem

Once a foreground service is started, the notification cannot be updated. The service must be stopped and restarted to apply updates to the notification.

### Preferred solution

Expose a plugin method that allows for updating the notification payload.

### Before submitting

- [X] I have read and followed the [feature request guidelines](https://capawesome.io/contributing/feature-requests/).
- [X] I have attached links to possibly related issues and discussions.

**Comment by robingenz** [comment]
Yes, this feature is currently missing.
