### ISSUE TITLE
feat(printer): add web support

### ISSUE THREAD

**Issue by macsupport** [capawesome-team/capacitor-plugins#331]
### Plugin(s)

- [ ] Android Foreground Service
- [ ] Android Battery Optimization
- [ ] App Review
- [ ] App Update
- [ ] Background Task
- [ ] Badge
- [ ] Bluetooth Low Energy
- [ ] Cloudinary
- [ ] Datetime Picker
- [ ] File Compressor
- [ ] File Opener
- [ ] File Picker
- [ ] Live Update
- [ ] Managed Configurations
- [ ] NFC
- [ ] Photo Editor
- [X] Printer
- [ ] Screen Orientation
- [ ] Speech Recognition
- [ ] Speech Synthesis
- [ ] Torch
- [ ] Zip

### Current problem

Printer plugin does not include web

### Preferred solution

Have printer plugin support iOS, Android and Web. 

### Alternative options

It would be a great option to add the ability to print a specific element in the Webview. Ideally targeted by an 'id'. The old Cordova printer plugin was able to do this, I think.

https://github.com/katzer/cordova-plugin-printer

### Before submitting

- [X] I have read and followed the [feature request guidelines](https://capawesome.io/contributing/feature-requests/).
- [X] I have attached links to possibly related issues and discussions.

**Comment by robingenz** [comment]
Thank you for your request! So is your issue about the web platform being supported or that you can select a specific element by ID when printing the WebView on Android and iOS? These are two different things.

**Comment by macsupport** [comment]
Sorry for the confusion. I was specifically asking for web support. I
previously used the cordova printer plugin to target printing a specific id
on a page in device and web. It was just a comment/suggestion. I also was
able to include print.css but that may be too much to ask!

Mike Sozanski DVM, DABVP

Check out my Veterinary Calculators: vetcalculators.com
<http://www.vetcalculators.com>
iOS <https://itunes.apple.com/us/app/vetcalculators/id1403466061?ls=1&mt=8>
and Android
<https://play.google.com/store/apps/details?id=com.vetcalculators.android>App
Available

**Comment by robingenz** [comment]
Thanks for the clarification. I will have a look at the issue at the weekend. That shouldn't be too much work.

**Comment by robingenz** [comment]
@macsupport I've just added web support for the `printWebView()` method.  You can use a print style sheet to customize the print output, see https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_media_queries/Printing.

Feel free to give it a try using the following dev version: 

```
npm i @capawesome-team/capacitor-printer@6.1.0-dev.202a1b7.1732369163
```

Let me know if you encounter any issues.
