### ISSUE TITLE
bug: Dependency conflict upon reinstalling packages

### ISSUE THREAD

**Issue by StefanoVe** [capawesome-team/capacitor-plugins#36]
### Plugin(s)

- [ ] App Update
- [X] Background Task
- [ ] Badge
- [ ] Cloudinary
- [ ] File Picker
- [ ] Managed Configurations
- [ ] Photo Editor
- [ ] Screen Orientation

### Did you test the latest version?

- [X] I use the latest version

### Platform(s)

- [X] Android
- [X] iOS
- [X] Web

### Current behavior

installing npm packages on the Capacitor 5 beta with background-task already in the dependency manifest causes a conflict with capacitor core. This does not happen however if background-task is installed after `npm install` using `npm i @capawesome/capacitor-background-task@2.0.0-dev.8c05008.1680891292`

```zsh
npm ERR! Found: @capacitor/core@5.0.0-beta.3
npm ERR! node_modules/@capacitor/core
npm ERR!   @capacitor/core@"next" from the root project
npm ERR!   peer @capacitor/core@"^5.0.0-beta.2" from @capacitor/android@5.0.0-beta.3
npm ERR!   node_modules/@capacitor/android
npm ERR!     @capacitor/android@"next" from the root project
npm ERR!   6 more (@capacitor/app, @capacitor/haptics, @capacitor/ios, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! @capawesome/capacitor-background-task@"^2.0.0-dev.8c05008.1680891292" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: @capacitor/core@4.8.0
npm ERR! node_modules/@capacitor/core
npm ERR!   peer @capacitor/core@"^4.0.0" from @capawesome/capacitor-background-task@2.0.0
npm ERR!   node_modules/@capawesome/capacitor-background-task
npm ERR!     @capawesome/capacitor-background-task@"^2.0.0-dev.8c05008.1680891292" from the root project
```

### Expected behavior

there shouldn't be any conflict with capacitor 5

### Reproduction

https://github.com/StefanoVe/background-task-dep-bug

### Steps to reproduce

1. Migrate to Capacitor 5 beta
2.run "npm i @capawesome/capacitor-background-task@2.0.0-dev.8c05008.1680891292"
3. run "rm -rf node_modules package_lock.json"
4. run "npm i"

### Capacitor doctor
```zsh
warn] The bundledWebRuntime configuration option has been deprecated. Can be safely
       deleted.
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.8.0
  @capacitor/core: 4.8.0
  @capacitor/android: 4.8.0
  @capacitor/ios: 4.8.0

Installed Dependencies:

  @capacitor/cli: 5.0.0-beta.3
  @capacitor/core: 5.0.0-beta.3
  @capacitor/android: 5.0.0-beta.3
  @capacitor/ios: 5.0.0-beta.3

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Before submitting

- [X] I understand that incomplete issues (e.g. without reproduction) are closed.

**Comment by robingenz** [comment]
Change your `package.json` as follows:

```diff
-    "@capawesome/capacitor-background-task": "^2.0.0-dev.8c05008.1680891292",
+    "@capawesome/capacitor-background-task": "2.0.0-dev.8c05008.1680891292",
```

(Remove the `^`)

**Comment by StefanoVe** [comment]
It works, thanks for the quick reply!
