### ISSUE TITLE
bug: FilePicker.pickFiles does not return anything on Android 13+ targeting SDK 33+

### ISSUE THREAD

**Issue by garrensweet** [capawesome-team/capacitor-plugins#40]
### Plugin(s)

- [ ] App Update
- [ ] Background Task
- [ ] Badge
- [ ] Cloudinary
- [ ] Datetime Picker
- [ ] File Opener
- [X] File Picker
- [ ] Managed Configurations
- [ ] Photo Editor
- [ ] Screen Orientation

### Did you test the latest version?

- [X] I use the latest version

### Platform(s)

- [X] Android
- [ ] iOS
- [ ] Web

### Current behavior

When utilizing the `FilePicker.pickFiles` method, nothing is returned after selecting a file in the new application window that appears.

```
const openFilePicker = async () => {
  const result = await FilePicker.pickFiles({
    types: ['application/pdf', 'image/png', 'image/jpeg', 'image/gif', 'image/tiff'],
    multiple: true,
  })

  console.log(result.files);
}
```

### Expected behavior

The value of `result.files` is an array of file paths.

### Reproduction

https://github.com/garrensweet/cap-file-picker

### Steps to reproduce

1. npm install
2. ionic cap sync android
3. gradle sync
4. build app
5. click 'Select Image'
6. Choose an image
7. Nothing happens

### Capacitor doctor

Latest Dependencies:

  @capacitor/cli: 5.0.5
  @capacitor/core: 5.0.5
  @capacitor/android: 5.0.5
  @capacitor/ios: 5.0.5

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 5.0.5
  @capacitor/core: 5.0.5
  @capacitor/android: 5.0.5

### Before submitting

- [X] I understand that incomplete issues (e.g. without reproduction) are closed.

**Comment by robingenz** [comment]
Unfortunately, I cannot reproduce your problem. I tested it with a Pixel 6a and Android 13.

<img width="816" alt="Bildschirmfoto 2023-06-21 um 14 17 45" src="https://github.com/capawesome-team/capacitor-plugins/assets/13857929/a806f1a9-48f5-485f-b576-d0af92a3bc5e">

**Comment by garrensweet** [comment]
@nicolashimmelmann I had the exact same problem.

I should note that this error you received:

```
W  OnBackInvokedCallback is not enabled for the application.
 Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
```                                                                          

Does not solve the problem, as I've done this already.

**Comment by robingenz** [comment]
Sorry, i can still not reproduce it. Maybe it's an issue with your device. But in this case i cannot debug it. PRs are welcome.


https://github.com/capawesome-team/capacitor-plugins/assets/13857929/e6d1aab9-773b-43b5-95c8-98f172640288

**Comment by garrensweet** [comment]
I'm closing this task.

The issue is not in this plugin, but actually in Capacitor's core. I'll file an issue over there with my findings. 

Thanks for your review @robingenz
