### ISSUE TITLE
bug: Execution failed for task ':app:checkReleaseDuplicateClasses'

### ISSUE THREAD

**Issue by lucasschulte** [capawesome-team/capacitor-plugins#46]
### Plugin(s)

- [X] App Update
- [ ] Background Task
- [ ] Badge
- [ ] Cloudinary
- [ ] Datetime Picker
- [ ] File Opener
- [ ] File Picker
- [ ] Managed Configurations
- [ ] Photo Editor
- [ ] Screen Orientation

### Did you test the latest version?

- [X] I use the latest version

### Platform(s)

- [X] Android
- [ ] iOS
- [ ] Web

### Current behavior

I have encountered the following error stack trace while attempting to install the app after successfully installing the package. Regrettably, I have been unable to find a solution that resolves the issue.

Duplicate class com.google.android.play.core.common.IntentSenderForResultStarter found in modules core-1.9.0-runtime (com.google.android.play:core:1.9.0) and core-common-2.0.2-runtime (com.google.android.play:core-common:2.0.2)
Duplicate class com.google.android.play.core.common.LocalTestingException found in modules core-1.9.0-runtime (com.google.android.play:core:1.9.0) and core-common-2.0.2-runtime (com.google.android.play:core-common:2.0.2)
Duplicate class com.google.android.play.core.common.PlayCoreDialogWrapperActivity found in modules core-1.9.0-runtime (com.google.android.play:core:1.9.0) and core-common-2.0.2-runtime (com.google.android.play:core-common:2.0.2)
Duplicate class com.google.android.play.core.listener.StateUpdatedListener found in modules core-1.9.0-runtime (com.google.android.play:core:1.9.0) and core-common-2.0.2-runtime (com.google.android.play:core-common:2.0.2)
Duplicate class com.google.android.play.core.review.ReviewInfo found in modules core-1.9.0-runtime (com.google.android.play:core:1.9.0) and review-2.0.1-runtime (com.google.android.play:review:2.0.1)
Duplicate class com.google.android.play.core.review.ReviewManager found in modules core-1.9.0-runtime (com.google.android.play:core:1.9.0) and review-2.0.1-runtime (com.google.android.play:review:2.0.1)
Duplicate class com.google.android.play.core.review.ReviewManagerFactory found in modules core-1.9.0-runtime (com.google.android.play:core:1.9.0) and review-2.0.1-runtime (com.google.android.play:review:2.0.1)
Duplicate class com.google.android.play.core.review.testing.FakeReviewManager found in modules core-1.9.0-runtime (com.google.android.play:core:1.9.0) and review-2.0.1-runtime (com.google.android.play:review:2.0.1)

### Expected behavior

I would like to be able to install the app or find a workaround for it.

### Reproduction

https://github.com/lucasschulte/capacitor-rate-update-bug 

### Steps to reproduce

EDIT: I was able to reproduce the problem. It is probably due to the combination with another package "capacitor-rate-update" and Capacitor 5

### Capacitor doctor

💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 5.1.0
  @capacitor/core: 5.1.0
  @capacitor/android: 5.1.0
  @capacitor/ios: 5.1.0

Installed Dependencies:

  @capacitor/core: 5.1.0
  @capacitor/ios: 5.1.0
  @capacitor/cli: 5.1.0
  @capacitor/android: 5.1.0

[success] iOS looking great! 👌
[error] Missing <manifest package=""> attribute in app/src/main

### Before submitting

- [X] I understand that incomplete issues (e.g. without reproduction) are closed.

**Comment by robingenz** [comment]
Thank you for your request.
Please provide a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) using [this template](https://github.com/capawesome-team/.capacitor-app) in a public GitHub repository so I can debug the issue.

**Comment by lucasschulte** [comment]
I have provided a sample repository for this issue and updated the issue ticket

**Comment by robingenz** [comment]
@lucasschulte Thank you. I can reproduce the issue. I will publish a fix soon.

**Comment by robingenz** [comment]
@cswagerty Best is not to change anything in the `variables.gradle` and let the plugin handle the versions.
If that does not help, please provide a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) using [this template](https://github.com/capawesome-team/.capacitor-app) in a public GitHub repository so I can debug the issue.

**Comment by cswagerty** [comment]
Hey @robingenz, I was able to recreate the issue using your MRE template here: https://github.com/cswagerty/capacitor-app-update-dependency-mre. The README has full info but TLDR is that the capacitor-rate-app (https://github.com/Nodonisko/capacitor-rate-app) has a dependency on `com.google.android.play:core:1.10.3` that is causing the `checkReleaseDuplicateClasses` gradle task to fail.

Thanks so much for your help, and if this is better suited to a new issue I'd be happy to create it!

**Comment by robingenz** [comment]
@cswagerty You just need to update `capacitor-rate-app` to version `4.0.3`.

**Comment by cswagerty** [comment]
@robingenz Confirmed that the upgrade of `capacitor-rate-app` to latest fixes the issue. Thank you so much for your help and all of your work on the plugin!
