### ISSUE TITLE
feat (cloudinary): Add Cloudinary AI Background Removal feature to the upload function

### ISSUE THREAD

**Issue by RobSchilderr** [capawesome-team/capacitor-plugins#50]
### Current problem

Currently, the `cloudinary` package in the `capacitor-plugins` repository does not support the Cloudinary AI Background Removal feature during the upload process. This feature is particularly useful for users who need to automatically remove the background of images during the upload process, saving them the time and effort of manually editing the images.

### Preferred solution

I propose to add the Cloudinary AI Background Removal feature to the upload function of the `cloudinary` package. This feature should be activated by setting the `background_removal` parameter to `cloudinary_ai` during the upload process.

### Alternative options

An alternative, as suggested by the [Cloudinary documentation](https://cloudinary.com/documentation/cloudinary_ai_background_removal_addon#removing_the_background_on_upload_update), is to remove the background on-the-fly by specifying the background_removal effect in the image URL. However, this would not automatically remove the background during the upload process, but rather when the image is delivered or displayed.

### Additional context

The Cloudinary AI Background Removal feature is a powerful tool that uses AI to automatically remove the background of images. More information about this feature can be found in the [Cloudinary documentation](https://cloudinary.com/documentation/cloudinary_ai_background_removal_addon#removing_the_background_on_upload_update).

**Comment by RobSchilderr** [comment]
I'm currently working on implementing this feature and have made some progress.

Right now, I am still in the process of testing these changes before I make an official PR. 

You can follow the progress of this work on my fork: [capacitor-plugins (background-removal branch)](https://github.com/RobSchilderr/capacitor-plugins/tree/background-removal)

**Comment by robingenz** [comment]
Yes, signed uploads are not supported by this plugin at the moment but it is planned. Unfortunately there is no ETA.
