### ISSUE TITLE
bug: file-opener - forbidden 403 on download

### ISSUE THREAD

**Issue by muuvmuuv** [capawesome-team/capacitor-plugins#53]
### Plugin(s)

- [ ] App Update
- [ ] Background Task
- [ ] Badge
- [ ] Cloudinary
- [ ] Datetime Picker
- [X] File Opener
- [ ] File Picker
- [ ] Managed Configurations
- [ ] Photo Editor
- [ ] Screen Orientation

### Did you test the latest version?

- [X] I use the latest version

### Platform(s)

- [ ] Android
- [ ] iOS
- [ ] Web

### Current behavior

```
pnpm add @capawesome-team/capacitor-file-opener
 ERR_PNPM_FETCH_403  GET https://npm.pkg.github.com/@capawesome-team%2Fcapacitor-file-opener: Forbidden - 403

This error happened while installing a direct dependency of xxxxxx

An authorization header was used: Bearer gith[hidden]

These authorization settings were found:
//npm.pkg.github.com/:_authToken=gith[hidden]
@capawesome-team:registry=https://npm.pkg.github.com/
@fortawesome:registry=https://npm.fontawesome.com/
//npm.fontawesome.com/:_authToken=F172[hidden]
```

### Expected behavior

Should be found

### Reproduction

...

### Steps to reproduce

1. Add the package

### Capacitor doctor

Latest Dependencies:
  @capacitor/cli: 5.2.1
  @capacitor/core: 5.2.1
  @capacitor/android: 5.2.1
  @capacitor/ios: 5.2.1
Installed Dependencies:
  @capacitor/cli: 5.2.1
  @capacitor/core: 5.2.1
  @capacitor/android: 5.2.1
  @capacitor/ios: 5.2.1

### Before submitting

- [X] I understand that incomplete issues (e.g. without reproduction) are closed.

**Comment by robingenz** [comment]
Thank you for your request.
If you are an [Insider](https://capawesome.io/insiders/#what-is-insiders), please take a look at the [Common issues](https://capawesome.io/insiders/getting-started/#common-issues) section.

If you are **not** an Insider, please install the package from the public npm registry:

```
npm install @capawesome-team/capacitor-file-opener
npx cap sync
```

In this case you do **not** need the following configuration:

```
//npm.pkg.github.com/:_authToken=gith[hidden]
@capawesome-team:registry=https://npm.pkg.github.com/
```

**Comment by muuvmuuv** [comment]
Ohh, there is a difference in the npm namespace-prefix, did not notice that. We already have "capacitor-badge" installed where it did not report an issue because it is a different one. Makes sense! Thanks! :)
