### ISSUE TITLE
bug: in-app update not working

### ISSUE THREAD

**Issue by dhruvi7489** [capawesome-team/capacitor-plugins#57]
### Plugin(s)

- [ ] Android Foreground Service
- [ ] Android Battery Optimization
- [X] App Update
- [ ] Background Task
- [ ] Badge
- [ ] Cloudinary
- [ ] Datetime Picker
- [ ] File Opener
- [ ] File Picker
- [ ] Managed Configurations
- [ ] NFC
- [ ] Photo Editor
- [ ] Screen Orientation

### Did you test the latest version?

- [X] I use the latest version

### Platform(s)

- [X] Android
- [X] iOS
- [ ] Web

### Current behavior

i'm trying to use @capawesome/capacitor-app-update to update my ionic app with playstore app.

My playstore apk version is '1.0.32'.
And new build that i made with version :'1.0.33'

When i call AppUpdate.getAppUpdateInfo() then in response i'm getting currentVersion:'33' and availableVersion:'33' and all update allowing variables giving false values.
<img width="296" alt="Screenshot 2023-07-19 161324" src="https://github.com/capawesome-team/capacitor-plugins/assets/105484910/973fd8d5-e6a1-4744-9874-64e29fd50ef7">

### Expected behavior

Need to update app inside my ionic app, just click on one button("app update").

Like if my previously play store installed app version is 1.0.32 then if i click on "app update" button from my app then it's automatically update with latest version that is newly available in play store. 
<img width="548" alt="image" src="https://github.com/capawesome-team/capacitor-plugins/assets/105484910/a263dbe1-1451-45b7-bae5-ae7a4580056f">

### Reproduction

https://github.com/dhruvi7489/ionic-in-app-update.git

### Steps to reproduce

1. uat environment
2. run with ionic s
3. build with 
ionic build
Ionic cap sync android
ionic cap open android
4. build signed apk with signature
5. run in real device

### Capacitor doctor

<img width="435" alt="image" src="https://github.com/capawesome-team/capacitor-plugins/assets/105484910/e6fec4de-1918-4543-907f-ebb84dd0b74f">

### Before submitting

- [X] I understand that incomplete issues (e.g. without reproduction) are closed.

**Comment by dhruvi7489** [comment]
Please help me to solve this ASAP

**Comment by dhruvi7489** [comment]
Please help me to solve this ASAP

**Comment by robingenz** [comment]
First of all, please note that this plugin currently only supports Capacitor 5, but you are using a mixture of Capacitor 3 and 4. 
Apart from that, the result seems to be correct. The `availableVersion` and `currentVersion` are the Android version code. This is in your project `33` (see [here](https://github.com/dhruvi7489/ionic-in-app-update/blob/9b33b179f1eb77e2ddf59aa817fc91badacb9333/android/app/build.gradle#L9C9-L9C20)).
Also, it can take a few days until the Play Store SDK detects a new update (see this [SO answer](https://stackoverflow.com/a/56383353/6731412)).

**Comment by dhruvi7489** [comment]
Hi @robingenz i understand your point but in this project there is other plugins also added. if I'll increase capacitor version from 3&4 to 5 then it might be affect that plugins and it's make complication in currently running project, so can you tell me is there any other way to implement in-app update functionality in capacitor 3&4.

**Comment by robingenz** [comment]
As i said, the result seems to be correct. The `availableVersion` and `currentVersion` are the Android version code. This is in your project `33` (see [here](https://github.com/dhruvi7489/ionic-in-app-update/blob/9b33b179f1eb77e2ddf59aa817fc91badacb9333/android/app/build.gradle#L9C9-L9C20)).

I assume that everything works as expected. You should make sure that you test the plugin properly, see [Test with internal app-sharing](https://capawesome.io/plugins/app-update/#test-with-internal-app-sharing).

**Comment by dhruvi7489** [comment]
But my apk already uploaded to playstore and that apk version is 1.0.32 , so if i upload new apk with version 1.0.33 then what should be availableVersion  & currentVersion ?

And if i built one apk with 1.0.31 and if i run locally then also it's give me availableVersion  & currentVersion is 1.0.31.

And is there any specific way to test this in-app update functionality locally?

**Comment by robingenz** [comment]
The Android version code is always a positive integer, see [Version settings](https://developer.android.com/studio/publish/versioning#versioningsettings).

You can only test it using this guide: https://developer.android.com/guide/playcore/in-app-updates/test
