### ISSUE TITLE
bug: unable to open file natively with file://

### ISSUE THREAD

**Issue by muuvmuuv** [capawesome-team/capacitor-plugins#62]
### Plugin(s)

- [ ] Android Foreground Service
- [ ] Android Battery Optimization
- [ ] App Update
- [ ] Background Task
- [ ] Badge
- [ ] Cloudinary
- [ ] Datetime Picker
- [X] File Opener
- [ ] File Picker
- [ ] Managed Configurations
- [ ] NFC
- [ ] Photo Editor
- [ ] Screen Orientation

### Did you test the latest version?

- [X] I use the latest version

### Platform(s)

- [X] Android
- [ ] iOS
- [ ] Web

### Current behavior

We have configured the file_paths.xml

```xml
<files-path name="files" path="./" />
<files-path name="config-files" path="config-files/" />
```

Through Filesystem plugin we have this `file://` url. But unfortunately I cannot get any `content://` file url for android which is specified in the API docs. Therefore it does not open in Acrobat or open the native Choose-Menu.

```
file:///data/user/0/<package>/files/config-files/e5652955d21e04e647ad686492d19.pdf
```

From my understanding I just need to ref the sub-dir "config-files" so other apps can have access to this files underneath. Is this correct?

### Expected behavior

Opens PDF. More detailed information about file_path.xml and acceptance of `file://`.

### Reproduction

Will create one if needed but I think its just configuration

### Steps to reproduce

1. Open PDF saved in /files/sub-dir/

### Capacitor doctor

Latest Dependencies:
  @capacitor/cli: 5.2.2
  @capacitor/core: 5.2.2
  @capacitor/android: 5.2.2
  @capacitor/ios: 5.2.2
Installed Dependencies:
  @capacitor/cli: 5.2.2
  @capacitor/core: 5.2.2
  @capacitor/android: 5.2.2
  @capacitor/ios: 5.2.2

### Before submitting

- [X] I understand that incomplete issues (e.g. without reproduction) are closed.

**Comment by robingenz** [comment]
Thank you for your request.
I need more information to be able to help you. What error message is thrown? 
How do you call the plugin and what values are passed?

**Comment by muuvmuuv** [comment]
Oh my.... it works. You told me earlier I need Acrobat and I indeed installed it before... but on a different simulator for testing. I upgrade to the new Android Studio UI today, and they have messed up my simulators, so it started the old once and deleted the new. Argh. Sorry.

This line did it: 

```xml
<files-path name="config-files" path="config-files/" />
```

**Comment by muuvmuuv** [comment]
Ok, so I have a device here (SM-T220 R9PR80393KX) where these errors occur on the latest Android (API 33) with Acrobat installed. Other apps can open PDF's in Acrobat. Any idea? Config seems to be fine. I cannot find anything else on the web than the files-path or to install a PDF-Viewer app.

**Comment by robingenz** [comment]
No, it should be a configuration problem. I use the plugin myself on SDK 33 and it works without problems. Maybe it's only an issue with a specific directory. Can you open a pdf from the Android downloads folder for example?

**Comment by muuvmuuv** [comment]
If I download a file from the web into the downloads dir, yes, it opens in Acrobat. From within the app it does not. I will try to figure out whats happening but cannot see the error that the plugin receives. Any debug flag I can put on?

**Comment by robingenz** [comment]
No, unfortunately not. But in this case it should be related to the paths you can configure in your app.

**Comment by muuvmuuv** [comment]
@robingenz for PDF's with Acrobat I had to add this query:

```xml

    <intent>
      <action android:name="android.intent.action.VIEW" />
      <data android:mimeType="application/pdf" />
    </intent>

**Comment by robingenz** [comment]
@muuvmuuv Thanks for sharing. Yes that's because of the mime type.
