### ISSUE TITLE
bug: Error: File cannot be opened

### ISSUE THREAD

**Issue by timKraeuter** [capawesome-team/capacitor-plugins#63]
### Plugin(s)

- [ ] Android Foreground Service
- [ ] Android Battery Optimization
- [ ] App Update
- [ ] Background Task
- [ ] Badge
- [ ] Cloudinary
- [ ] Datetime Picker
- [X] File Opener
- [ ] File Picker
- [ ] Managed Configurations
- [ ] NFC
- [ ] Photo Editor
- [ ] Screen Orientation

### Did you test the latest version?

- [X] I use the latest version

### Platform(s)

- [X] Android
- [ ] iOS
- [ ] Web

### Current behavior

I run the plugin demo and open a file from the downloads folder of my simulator. Then when I use the file opener to open the file I get the following error:

```
2023-08-05 14:35:57.452 28539-28539 Capacitor               dev.robingenz.capacitor.plugindemo   V  callback: 91063589, pluginId: FileOpener, methodName: openFile, methodData: {"path":"content:\/\/com.android.providers.downloads.documents\/document\/msf%3A1000000038"}
2023-08-05 14:35:57.491 28539-28611 Capacitor               dev.robingenz.capacitor.plugindemo   D  Sending plugin error: {"save":false,"callbackId":"91063589","pluginId":"FileOpener","methodName":"openFile","success":false,"error":{"message":"File cannot be opened."}}
2023-08-05 14:35:57.495 28539-28559 EGL_emulation           dev.robingenz.capacitor.plugindemo   D  app_time_stats: avg=380.47ms min=9.26ms max=1398.08ms count=4
2023-08-05 14:35:57.516 28539-28539 Capacitor/Console       dev.robingenz.capacitor.plugindemo   E  File: http://localhost/main.0744f8895edac34a.js - Line 1 - Msg: Error: Uncaught (in promise): Error: File cannot be opened.
                                                                                                    Error: File cannot be opened.
                                                                                                        at returnResult (http://localhost/:846:32)
                                                                                                        at win.androidBridge.onmessage (http://localhost/:821:21)
```

### Expected behavior

I expect the file to be opened on the device.

### Reproduction

https://github.com/robingenz/capacitor-plugin-demo

### Steps to reproduce

1. Clone the demo repo https://github.com/robingenz/capacitor-plugin-demo.
2. Installation (npm i, npm build, npx cap sync)
3. Run the APP on a virtual device (Android 34 used)
4. Select a file and then try to open it using the app.

### Capacitor doctor

$ npx cap doctor
[warn] The bundledWebRuntime configuration option has been deprecated. Can be safely deleted.
Latest Dependencies:       

  @capacitor/cli: 5.2.2    
  @capacitor/core: 5.2.2   
  @capacitor/android: 5.2.2
  @capacitor/ios: 5.2.2    

Installed Dependencies:

  @capacitor/cli: 5.2.2
  @capacitor/core: 5.2.2
  @capacitor/android: 5.2.2
  @capacitor/ios: 5.2.2

[error] Missing <manifest package=""> attribute in app/src/main

### Before submitting

- [X] I understand that incomplete issues (e.g. without reproduction) are closed.

**Comment by robingenz** [comment]
You need to install an app on the emulator which can open this specific file type, e.g. Adobe Acrobat for pdf files.

**Comment by timKraeuter** [comment]
I installed a PDF reader on the AVD but still got the same error. When I use my physical device (Android 13) I am able to open pictures but still cannot open PDF files (Same error as above).

**Comment by robingenz** [comment]
You can take a look at the code: https://github.com/capawesome-team/capacitor-plugins/blob/c3cdea4b4f7969642ad7b2b1e4ef302a683a0e2b/packages/file-opener/android/src/main/java/io/capawesome/capacitorjs/plugins/fileopener/FileOpenerPlugin.java#L45
The error is thrown only if no application was found that can open the file.
Please also make sure that you have specified the directories that contain the files you want to open, see https://capawesome.io/plugins/file-opener/#android.

**Comment by timKraeuter** [comment]
Hmm, that's weird. I have plenty of PDF readers installed on my physical device and have written the file with the same app. I can also read the file using the FileSystem capacitor API.
Not sure what is happening, but I will check back again soon.

Does opening a PDF work for you with the file opener?

**Comment by robingenz** [comment]
Yes. There was a similar issue recently (see #54).

**Comment by robingenz** [comment]
@RobSchilderr Can you provide a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) using [this template](https://github.com/capawesome-team/.capacitor-app) and the corresponding pdf file in a public GitHub repository?
I just tested it with version `5.0.2` and it worked for me.

**Comment by timKraeuter** [comment]
For me, the capacitor plugin demo works now after adding the following under <queries> in the manifest:

``` xml
<intent>
      <action android:name="android.intent.action.VIEW" />
      <category android:name="android.intent.category.BROWSABLE" />
      <data android:scheme="https" />
</intent>
```
I found the answer in this [StackOverflow post](https://stackoverflow.com/questions/62535856/intent-resolveactivity-returns-null-in-api-30). It seems to be due to a change introduced in android 11. I was testing with android 13 so it caused problems in my case.

**Comment by RobSchilderr** [comment]
> ```
> android.intent.action.VIEW
> ```

This indeed also fixes my issue.

**Comment by RobSchilderr** [comment]
> For me, the capacitor plugin demo works now after adding the following under `<queries>` in the manifest:
> 
> ```
> <intent>
>       <action android:name="android.intent.action.VIEW" />
>       <category android:name="android.intent.category.BROWSABLE" />
>       <data android:scheme="https" />
> </intent>
> ```
> 
> I found the answer in this [StackOverflow post](https://stackoverflow.com/questions/62535856/intent-resolveactivity-returns-null-in-api-30). It is due to a **change introduced in Android 11**. I was testing with Android 13, so it was the problem in my case.

This indeed also fixed my issue, so I won't make a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) for now @robingenz.

**Comment by robingenz** [comment]
Thank you @timKraeuter  and @RobSchilderr!
I just updated my emulator and now i can reproduce the issue.
I will update the documentation.

**Comment by eranshmil** [comment]
I'm experiencing something similar after upgrading to Capacitor 5.
PDF works just fine but docx/doc not, I added the `queries` element but still nothing.
```xml
<queries>
  <intent>
    <action android:name="android.intent.action.VIEW" />
    <category android:name="android.intent.category.BROWSABLE" />
    <data android:scheme="https" />
  </intent>
</queries>
```

`file_paths.xml`:
```xml
<?xml version="1.0" encoding="utf-8"?>
<paths xmlns:android="http://schemas.android.com/apk/res/android">
  <files-path name="files" path="." />
  <cache-path name="cache" path="." />
  <external-files-path name="external-files" path="." />
  <external-cache-path name="external-cache" path="." />
  <external-path name="external" path="." />
</paths>
```

Only the following permission solves it, but I read that it's not a good practice.
```xml
<uses-permission android:name="android.permission.QUERY_ALL_PACKAGES" />
```

**Comment by robingenz** [comment]
@eranshmil Thank you for your input. I will take another look.
