### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by ecc521** [capawesome-team/capacitor-plugins#65]
### Plugin(s)

- [ ] Android Foreground Service
- [ ] Android Battery Optimization
- [X] App Update
- [ ] Background Task
- [ ] Badge
- [ ] Cloudinary
- [ ] Datetime Picker
- [ ] File Opener
- [ ] File Picker
- [ ] Managed Configurations
- [ ] NFC
- [ ] Photo Editor
- [ ] Screen Orientation

### Did you test the latest version?

- [X] I use the latest version

### Platform(s)

- [ ] Android
- [X] iOS
- [ ] Web

### Current behavior

Created a release, with version 7 in XCode
Created release with version 7.0 in App Store Connect

Upon release, Capacitor App Update believes that there is an update from version 7 to 7.0, even though they are the same. 

### Expected behavior

No update should be available. 

### Reproduction

---

### Steps to reproduce

MCRE not really possible as requires publishing app. 

Example of issue (Safari Web Inspector on app)
<img width="843" alt="Screenshot 2023-08-07 at 4 13 57 PM" src="https://github.com/capawesome-team/capacitor-plugins/assets/42424091/d7bbe55c-38ef-45e6-b027-85f174daf7fc">

### Capacitor doctor

Latest Dependencies:

  @capacitor/cli: 5.2.2
  @capacitor/core: 5.2.2
  @capacitor/android: 5.2.2
  @capacitor/ios: 5.2.2

Installed Dependencies:

  @capacitor/cli: 5.2.2
  @capacitor/core: 5.2.2
  @capacitor/android: 5.2.2
  @capacitor/ios: 5.2.2

### Before submitting

- [X] I understand that incomplete issues (e.g. without reproduction) are closed.

**Comment by robingenz** [comment]
> Created a release, with version 7 in XCode
> Created release with version 7.0 in App Store Connect

This is the problem. You should name the versions consistently.

> Upon release, Capacitor App Update believes that there is an update from version 7 to 7.0, even though they are the same.

Besides that, the Capacitor App Update plugin only returns the version information. It does not tell you on iOS if an update is available or not. 
I recommend a package like https://www.npmjs.com/package/semver to compare the version numbers.

For this reason i am closing this issue.
