### ISSUE TITLE
bug: File Picker Sending Duplicate Images when Selecting Downloaded Images from IOS

### ISSUE THREAD

**Issue by danbunkr** [capawesome-team/capacitor-plugins#66]
### Plugin(s)

- [ ] Android Foreground Service
- [ ] Android Battery Optimization
- [ ] App Update
- [ ] Background Task
- [ ] Badge
- [ ] Cloudinary
- [ ] Datetime Picker
- [ ] File Opener
- [X] File Picker
- [ ] Managed Configurations
- [ ] NFC
- [ ] Photo Editor
- [ ] Screen Orientation

### Did you test the latest version?

- [X] I use the latest version

### Platform(s)

- [ ] Android
- [X] iOS
- [ ] Web

### Current behavior

I have a few GoPro images that I downloaded on IOS. When I select the files from IOS Photos despite being different files the file-picker plugin sends me 2 duplicate images. Ive attached screenshots of the image / info below. When these are selected I get the following from the File Picker plugin.

Capacitor Logs:

```
⚡️  TO JS {"files":[{"name":"GPTempDownload.heic","size":1146838,"height":3286,"mimeType":"image\/heic","width":4288,"modifiedAt":1690988208860,"path":"file:\/\/\/var\/mobile\/Containers\/Data\/Application\/F13934F8-6B20-4F64-98CA-0F5E02FA221B\/Library\/Caches\/GPTe
```

Received in the JS Layer:

```
[
  {
    "name": "GPTempDownload.heic",
    "size": 1146838,
    "height": 3286,
    "mimeType": "image/heic",
    "width": 4288,
    "modifiedAt": 1690988208860,
    "path": "file:///var/mobile/Containers/Data/Application/F13934F8-6B20-4F64-98CA-0F5E02FA221B/Library/Caches/GPTempDownload.heic"
  },
  {
    "name": "GPTempDownload.heic",
    "size": 1146838,
    "height": 3286,
    "mimeType": "image/heic",
    "width": 4288,
    "modifiedAt": 1690988208860,
    "path": "file:///var/mobile/Containers/Data/Application/F13934F8-6B20-4F64-98CA-0F5E02FA221B/Library/Caches/GPTempDownload.heic"
  }
]
```

![IMG_1845](https://github.com/capawesome-team/capacitor-plugins/assets/82471930/8d0a4634-65cd-4e34-912a-5a0c3c29fd49)
![IMG_1846](https://github.com/capawesome-team/capacitor-plugins/assets/82471930/8bca62b6-78e8-4f7c-a471-4c1bfe1a46be)

### Expected behavior

FilePIcker should not send duplicate images given the the files and different. My guess is it has something to do with the name being the same `GPTempDownload.heic` which appears to be the given Icloud name and not the actual name of the file. 

If needed I can provide the raw files.

### Reproduction

https://github.com/capawesome-team/.capacitor-app

### Steps to reproduce

Open FilePicker with GoPro Images or Images downloaded from Icloud on IOS.
Select the files
Observe that data is duplicated despite files being unique.

### Other information

It's hard to provide a reproduction because it has more to do with the files being selected. Again if needed I can provide the files directly to a member of the team. I think uploading them here would change the metadata that IOS provides.

Edited:

After doing a bit more research it turns out the files all have the same name GPTempDownload.heic and the caption is the unique value per the screenshots above. It seems like having duplicate names is throwing the logic off.

### Capacitor doctor

```
Latest Dependencies:

  @capacitor/cli: 5.2.2
  @capacitor/core: 5.2.2
  @capacitor/android: 5.2.2
  @capacitor/ios: 5.2.2

Installed Dependencies:

  @capacitor/cli: 5.0.5
  @capacitor/core: 5.2.2
  @capacitor/android: 5.2.2
  @capacitor/ios: 5.2.2
  ```

### Before submitting

- [X] I understand that incomplete issues (e.g. without reproduction) are closed.

**Comment by robingenz** [comment]
Yes, that would be an acceptable solution. But to be honest, I haven't quite figured out the problem yet, since I haven't had time to try it out myself. But a PR would definitely help me. I might suggest another solution then though. But then I could help with the implementation.

**Comment by danbunkr** [comment]
@robingenz  - I DM'd you on discord. But will leave the findings here as well for transparency. I traced the issue down to `saveTemporaryFile` function specifically `directory.appendingPathComponent(sourceUrl.lastPathComponent)` because when files have the same name / extension this will return the same value.

A function like:

```
   private func saveTemporaryFile(_ sourceUrl: URL) throws -> URL {
        var directory = URL(fileURLWithPath: NSTemporaryDirectory())
        if let cachesDirectory = FileManager.default.urls(for: .cachesDirectory, in: .userDomainMask).first {
            directory = cachesDirectory
        }
        
        var targetUrl = directory.appendingPathComponent(sourceUrl.lastPathComponent)
        let fileNameWithoutExtension = sourceUrl.deletingPathExtension().lastPathComponent
        let fileExtension = sourceUrl.pathExtension
        
        // Check if the target file already exists, and generate a unique filename if needed
        var counter = 1
        while FileManager.default.fileExists(atPath: targetUrl.path) {
            let uniqueFileName = "\(fileNameWithoutExtension)_\(counter).\(fileExtension)"
            targetUrl = directory.appendingPathComponent(uniqueFileName)
            counter += 1
        }
        
        // Remove any existing file at the target URL
        try? FileManager.default.removeItem(at: targetUrl)
        
        // Copy the source file to the target URL
        try FileManager.default.copyItem(at: sourceUrl, to: targetUrl)
        
        return targetUrl
    }
    
    ```
    
Would work but I'm open to refactor or tweaks ideas and then opening a PR

**Comment by danbunkr** [comment]
@robingenz - Per our discussions yesterday: https://github.com/capawesome-team/capacitor-plugins/pull/67 should fix this issue. My approach was to add create the fileURL for the temporary file as `UUID_FileName.extension` and then strip off the `UUID_` before sending it back to the JS layer
