### ISSUE TITLE
feat: File Picker pickerDismissed should provide info on the action

### ISSUE THREAD

**Issue by danbunkr** [capawesome-team/capacitor-plugins#68]
### Plugin(s)

- [ ] Android Foreground Service
- [ ] Android Battery Optimization
- [ ] App Update
- [ ] Background Task
- [ ] Badge
- [ ] Cloudinary
- [ ] Datetime Picker
- [ ] File Opener
- [X] File Picker
- [ ] Managed Configurations
- [ ] NFC
- [ ] Photo Editor
- [ ] Screen Orientation

### Current problem

I was trying to use the FilePicker pickerDismissed event to hook up some UI while files were processing. However, it fires the event when picker is cancelled. I've tried to work around it with various state updates but the logic gets very complicated and annoying to deal with. 

### Preferred solution

The way I see it we have two options:

1.) Picker Dismissed event should provide some basic data on the event. Such as either a dismiss due to cancel or dismiss due to files selected (add)
2.) Picker Dismissed could only fire if people actually selected files as most likely this event will be used to hook up UI around processing selected files.

**Comment by robingenz** [comment]
> However, it fires the event when picker is cancelled

Yes, but in this case the promise should be resolved before the event is fired. So you should just be able to check if the promise is already resolved or not and implement your logic depending on that.

**Comment by danbunkr** [comment]
That makes sense. Im gonna close this issue for now to not clog up open issues and we can revisit it later if others experience similar issues
