### ISSUE TITLE
feat: 

### ISSUE THREAD

**Issue by AEiosApp** [capawesome-team/capacitor-plugins#90]
### Plugin(s)

- [ ] Android Foreground Service
- [ ] Android Battery Optimization
- [X] App Update
- [ ] Background Task
- [ ] Badge
- [ ] Cloudinary
- [ ] Datetime Picker
- [ ] File Opener
- [ ] File Picker
- [ ] Managed Configurations
- [ ] NFC
- [ ] Photo Editor
- [ ] Screen Orientation

### Current problem

Would be great in **getAppUpdateInfo** method receive **what's new** text from App Store / Google Play

### Preferred solution

Would be great in **getAppUpdateInfo** method receive **what's new** text from App Store / Google Play

### Alternative options

Would be great in **getAppUpdateInfo** method receive **what's new** text from App Store / Google Play

**Comment by robingenz** [comment]
Thank you for your request! Unfortunately, as far as I know, there are no APIs to retrieve this information. For this reason, I am closing this issue.
