### ISSUE TITLE
request: New plugin, video recoder

### ISSUE THREAD

**Issue by josuelmm** [capawesome-team/capacitor-plugins#92]
### Plugin(s)

- [ ] Android Foreground Service
- [ ] Android Battery Optimization
- [ ] App Update
- [ ] Background Task
- [ ] Badge
- [ ] Cloudinary
- [ ] Datetime Picker
- [ ] File Opener
- [X] File Picker
- [ ] Managed Configurations
- [ ] NFC
- [ ] Photo Editor
- [ ] Screen Orientation

### Current problem

Nothing problem, only a request

### Preferred solution

Nothing problem, only a request

**Comment by robingenz** [comment]
Sorry, but "video recorder" is not enough information for a new plugin.

**Comment by josuelmm** [comment]
Video recorder from camera
