### ISSUE TITLE
feat: add `Background Audio` plugin

### ISSUE THREAD

**Issue by eckstaedt** [capawesome-team/capacitor-plugins#94]
### Name

Background Audio

### Platform(s)

- [X] Android
- [X] iOS
- [ ] Web

### Description

As a user I want to control my audio in Background via the Lock Screen for example.

**Comment by robingenz** [comment]
Thank you for your proposal!

There is already a Capacitor Community for native audio: https://github.com/capacitor-community/native-audio

How would your plugin differ from this one?

**Comment by eckstaedt** [comment]
Thanks for this hint. I will try this out!

**Comment by robingenz** [comment]
Alright, I close this issue for now.
