### ISSUE TITLE
feat: Add improved error handling and clear error messages for the `FileOpener.openFile()` function on iOS.

### ISSUE THREAD

**Issue by walweh** [capawesome-team/capacitor-plugins#95]
### Plugin(s)

- [ ] Android Foreground Service
- [ ] Android Battery Optimization
- [ ] App Update
- [ ] Background Task
- [ ] Badge
- [ ] Cloudinary
- [ ] Datetime Picker
- [X] File Opener
- [ ] File Picker
- [ ] Managed Configurations
- [ ] NFC
- [ ] Photo Editor
- [ ] Screen Orientation

### Current problem

The `FileOpener.openFile()` function currently lacks proper error handling and clear error messages on iOS. This makes it challenging for developers to identify and address issues when attempting to open files.

### Preferred solution

Implement improved error handling for the `FileOpener.openFile()` function on iOS. This could include providing meaningful error messages or error codes that developers can use to diagnose and resolve issues more effectively.

**Comment by robingenz** [comment]
Do you have any examples?

**Comment by walweh** [comment]
Current Behavior with .msg (application/vnd.ms-outlook)

On Android, the function works fine, providing either an error or successfully opening the file.
On iOS, the function doesn't throw any errors.

**Comment by robingenz** [comment]
Thanks for sharing!
This should be a bug. Therefore I close this feature request. Please create a bug report and provide a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) using [this template](https://github.com/capawesome-team/.capacitor-app) in a public GitHub repository so I can debug the issue.
Please also provide a sample `application/vnd.ms-outlook` file for testing.
